// Parity test for net.minecraft.world.item.BowItem.getPowerForTime (26.1.2).
// Ground truth generated by tools/BowItemPowerParity.java against the real class.
// The float result is exchanged as a raw IEEE-754 bit pattern and compared via
// std::bit_cast, so the gate is bit-for-bit exact.
//
//   bow_item_power_parity --cases mcpp/build/bow_item_power.tsv

#include "world/item/BowItemPower.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace bi = mc::item;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out; std::string it; std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32hex(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
// timeHeld can be Integer.MIN_VALUE (-2147483648), which overflows std::stoi/long
// on LLP64; parse as long long then narrow with the same two's-complement wrap
// the Java int has.
int32_t i32dec(const std::string& s) { return static_cast<int32_t>(std::stoll(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }
}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: bow_item_power_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0; int shown = 0;

    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "POW") {
            // POW <timeHeld:int> <resultBits:%08x>
            float got = bi::getPowerForTime(i32dec(p[1]));
            uint32_t exp = u32hex(p[2]);
            if (fb(got) != exp) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH POW timeHeld=" << p[1]
                              << " got=" << std::hex << fb(got)
                              << " exp=" << exp << std::dec << " | " << line << "\n";
            }
        } else {
            std::cerr << "unknown TAG: " << t << "\n";
            ++mism;
        }
    }

    std::cout << "BowItemPower checks=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
