// Parity test for the PURE placement-coordinate helpers
//   StructureTemplate.calculateRelativePosition / calculateConnectedPosition.
// Ground truth is generated by tools/StructureConnectedPositionParity.java
// against the real 26.1.2 classes (StructureTemplate + StructurePlaceSettings).
//
// Each TSV row carries its inputs and the expected output BlockPos; we recompute
// from the inputs via StructureConnectedPosition.h and compare in decimal ints.
//
//   structure_connected_position_parity --cases mcpp/build/structure_connected_position.tsv
//
// The REAL Bootstrap can log to stdout, so any line whose first tab-field is not a
// known tag (RELPOS / CONNPOS / CONNEDGE) is SKIPPED (not counted, not a mismatch).

#include "StructureConnectedPosition.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using namespace mc::levelgen::structure::templatesystem;
using mc::levelgen::structure::BlockPos;
using mc::levelgen::structure::Mirror;
using mc::levelgen::structure::Rotation;

namespace {

std::vector<std::string> splitTabs(const std::string& line) {
    std::vector<std::string> out;
    std::string item;
    std::istringstream ss(line);
    while (std::getline(ss, item, '\t')) out.push_back(item);
    return out;
}

// Java ints reach Integer.MIN/MAX_VALUE in the edge battery; stoll then narrow.
int toi(const std::string& s) { return static_cast<int>(std::stoll(s)); }

Mirror mir(int i) { return static_cast<Mirror>(i); }
Rotation rot(int i) { return static_cast<Rotation>(i); }

StructurePlaceSettings settings(int mIdx, int rIdx, const BlockPos& pivot) {
    return StructurePlaceSettings{mir(mIdx), rot(rIdx), pivot};
}

} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) { std::cerr << "usage: structure_connected_position_parity --cases <tsv>\n"; return 2; }

    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;

    auto fail = [&](const std::string& tag, const std::string& detail) {
        ++mism;
        if (shown++ < 40) std::cerr << "MISMATCH " << tag << " " << detail << "\n";
    };

    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto p = splitTabs(line);
        if (p.empty()) continue;
        const std::string& tag = p[0];

        if (tag == "RELPOS") {
            // RELPOS x y z m r pivX pivY pivZ  ox oy oz
            BlockPos o = calculateRelativePosition(
                settings(toi(p[4]), toi(p[5]), BlockPos{toi(p[6]), toi(p[7]), toi(p[8])}),
                BlockPos{toi(p[1]), toi(p[2]), toi(p[3])});
            ++total;
            if (o.x != toi(p[9]) || o.y != toi(p[10]) || o.z != toi(p[11]))
                fail(tag, line + " got=" + std::to_string(o.x) + "," + std::to_string(o.y) + "," + std::to_string(o.z));
        } else if (tag == "CONNPOS") {
            // CONNPOS x1 y1 z1 m1 r1 p1x p1y p1z  x2 y2 z2 m2 r2 p2x p2y p2z  ox oy oz
            BlockPos c1{toi(p[1]), toi(p[2]), toi(p[3])};
            BlockPos c2{toi(p[9]), toi(p[10]), toi(p[11])};
            BlockPos o = calculateConnectedPosition(
                settings(toi(p[4]), toi(p[5]), BlockPos{toi(p[6]), toi(p[7]), toi(p[8])}), c1,
                settings(toi(p[12]), toi(p[13]), BlockPos{toi(p[14]), toi(p[15]), toi(p[16])}), c2);
            ++total;
            if (o.x != toi(p[17]) || o.y != toi(p[18]) || o.z != toi(p[19]))
                fail(tag, line + " got=" + std::to_string(o.x) + "," + std::to_string(o.y) + "," + std::to_string(o.z));
        } else if (tag == "CONNEDGE") {
            // CONNEDGE c1x c1y c1z m r  c2x c2y c2z  ox oy oz
            // side1 = (mirror m, rotation r, pivot 0); side2 = (NONE, NONE, pivot 0).
            BlockPos c1{toi(p[1]), toi(p[2]), toi(p[3])};
            BlockPos c2{toi(p[6]), toi(p[7]), toi(p[8])};
            BlockPos o = calculateConnectedPosition(
                settings(toi(p[4]), toi(p[5]), BlockPos{0, 0, 0}), c1,
                settings(0, 0, BlockPos{0, 0, 0}), c2);
            ++total;
            if (o.x != toi(p[9]) || o.y != toi(p[10]) || o.z != toi(p[11]))
                fail(tag, line + " got=" + std::to_string(o.x) + "," + std::to_string(o.y) + "," + std::to_string(o.z));
        } else {
            // Unknown first field (e.g. Bootstrap log spew) — skip, do not count.
            continue;
        }
    }

    std::cout << "StructureConnectedPosition checks=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
