// Parity test for the PURE block-ordering helper
//   StructureTemplate.buildInfoList(fullBlockList, blockEntitiesList, otherBlocksList).
// Ground truth is generated by tools/StructureTemplateBuildInfoListParity.java,
// which reflectively drives the REAL private static method over the REAL
// StructureBlockInfo records (each tagged with a unique id in its NBT) and emits
// both the inputs and the produced id ordering.
//
// We reconstruct the three input lists per case from the IN rows (in emission
// order — emission order IS input order, which the stable sort must respect),
// run StructureTemplateBuildInfoList.h::buildInfoList, and compare the resulting
// id sequence against the OUT row exactly.
//
//   structure_template_build_info_list_parity --cases mcpp/build/structure_template_build_info_list.tsv
//
// The REAL Bootstrap can log to stdout, so any line whose first tab-field is not
// IN or OUT is SKIPPED (not counted, not a mismatch).

#include "StructureTemplateBuildInfoList.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using mc::levelgen::structure::templatesystem::BlockInfo;
using mc::levelgen::structure::templatesystem::buildInfoList;

namespace {

std::vector<std::string> splitTabs(const std::string& line) {
    std::vector<std::string> out;
    std::string item;
    std::istringstream ss(line);
    while (std::getline(ss, item, '\t')) out.push_back(item);
    return out;
}

// Java ints reach Integer.MIN/MAX_VALUE; parse wide then narrow to int32.
int32_t toi(const std::string& s) { return static_cast<int32_t>(std::stoll(s)); }

struct Case {
    // Three input lists in emission (input) order.
    std::vector<BlockInfo> full;          // listIdx 0
    std::vector<BlockInfo> blockEntities; // listIdx 1
    std::vector<BlockInfo> other;         // listIdx 2
    std::vector<int32_t> expected;        // expected output id sequence
    bool haveOut = false;
};

} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: structure_template_build_info_list_parity --cases <tsv>\n";
        return 2;
    }

    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    // Collect cases in first-seen order (caseId is dense from 0, but keep a map to
    // be robust to ordering of IN/OUT rows).
    std::map<int, Case> cases;
    std::vector<int> order;
    std::string line;

    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = splitTabs(line);
        if (p.empty()) continue;
        const std::string& tag = p[0];

        if (tag == "IN") {
            // IN caseId listIdx x y z id
            if (p.size() != 7) continue;
            int caseId = static_cast<int>(std::stoll(p[1]));
            int listIdx = static_cast<int>(std::stoll(p[2]));
            BlockInfo bi{toi(p[3]), toi(p[4]), toi(p[5]), toi(p[6])};
            auto it = cases.find(caseId);
            if (it == cases.end()) {
                order.push_back(caseId);
                it = cases.emplace(caseId, Case{}).first;
            }
            if (listIdx == 0) it->second.full.push_back(bi);
            else if (listIdx == 1) it->second.blockEntities.push_back(bi);
            else if (listIdx == 2) it->second.other.push_back(bi);
        } else if (tag == "OUT") {
            // OUT caseId n id0 id1 ...
            if (p.size() < 3) continue;
            int caseId = static_cast<int>(std::stoll(p[1]));
            int n = static_cast<int>(std::stoll(p[2]));
            auto it = cases.find(caseId);
            if (it == cases.end()) {
                order.push_back(caseId);
                it = cases.emplace(caseId, Case{}).first;
            }
            it->second.expected.clear();
            for (int k = 0; k < n && (3 + k) < static_cast<int>(p.size()); ++k)
                it->second.expected.push_back(toi(p[3 + k]));
            it->second.haveOut = true;
        } else {
            // Unknown first field (e.g. Bootstrap log spew) — skip, do not count.
            continue;
        }
    }

    long long total = 0, mism = 0;
    int shown = 0;

    for (int caseId : order) {
        const Case& c = cases[caseId];
        if (!c.haveOut) continue; // no expectation emitted; nothing to compare
        ++total;

        std::vector<BlockInfo> got = buildInfoList(c.full, c.blockEntities, c.other);

        bool ok = got.size() == c.expected.size();
        if (ok) {
            for (size_t k = 0; k < got.size(); ++k) {
                if (got[k].id != c.expected[k]) { ok = false; break; }
            }
        }
        if (!ok) {
            ++mism;
            if (shown++ < 40) {
                std::ostringstream os;
                os << "MISMATCH case=" << caseId << " expected[";
                for (size_t k = 0; k < c.expected.size(); ++k) os << (k ? "," : "") << c.expected[k];
                os << "] got[";
                for (size_t k = 0; k < got.size(); ++k) os << (k ? "," : "") << got[k].id;
                os << "]";
                std::cerr << os.str() << "\n";
            }
        }
    }

    std::cout << "StructureTemplateBuildInfoList checks=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
