// Parity test for net.minecraft.util.BinaryAnimator + EasingType + Ease.
// Ground truth generated by tools/BinaryAnimatorParity.java against the real
// 26.1.2 classes. Each row carries inputs + expected output; floats are exchanged
// as raw IEEE-754 bit patterns, so the gate is bit-exact.
//
//   binary_animator_parity --cases mcpp/build/binary_animator.tsv

#include "BinaryAnimator.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

namespace bau = mc::util;

namespace {

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}

uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }

// Ease.<name> -> function pointer (by the exact Java method name).
using EaseFn = float (*)(float);
const std::unordered_map<std::string, EaseFn>& easeByName() {
    static const std::unordered_map<std::string, EaseFn> m = {
        {"inBack", &bau::ease::inBack},       {"inBounce", &bau::ease::inBounce},
        {"inCubic", &bau::ease::inCubic},     {"inElastic", &bau::ease::inElastic},
        {"inExpo", &bau::ease::inExpo},       {"inQuart", &bau::ease::inQuart},
        {"inQuint", &bau::ease::inQuint},     {"inSine", &bau::ease::inSine},
        {"inOutBounce", &bau::ease::inOutBounce}, {"inOutCirc", &bau::ease::inOutCirc},
        {"inOutCubic", &bau::ease::inOutCubic},   {"inOutQuad", &bau::ease::inOutQuad},
        {"inOutQuart", &bau::ease::inOutQuart},   {"inOutQuint", &bau::ease::inOutQuint},
        {"outBounce", &bau::ease::outBounce}, {"outElastic", &bau::ease::outElastic},
        {"outExpo", &bau::ease::outExpo},     {"outQuad", &bau::ease::outQuad},
        {"outQuint", &bau::ease::outQuint},   {"outSine", &bau::ease::outSine},
        {"inOutSine", &bau::ease::inOutSine}, {"outBack", &bau::ease::outBack},
        {"outQuart", &bau::ease::outQuart},   {"outCubic", &bau::ease::outCubic},
        {"inOutExpo", &bau::ease::inOutExpo}, {"inQuad", &bau::ease::inQuad},
        {"outCirc", &bau::ease::outCirc},     {"inOutElastic", &bau::ease::inOutElastic},
        {"inCirc", &bau::ease::inCirc},       {"inOutBack", &bau::ease::inOutBack},
    };
    return m;
}

// EasingType.<NAME> -> function pointer (by the public field name).
const std::unordered_map<std::string, bau::EasingFn>& etypeByName() {
    using namespace bau::easing_type;
    static const std::unordered_map<std::string, bau::EasingFn> m = {
        {"CONSTANT", CONSTANT},   {"LINEAR", LINEAR},
        {"IN_BACK", IN_BACK},     {"IN_BOUNCE", IN_BOUNCE},   {"IN_CIRC", IN_CIRC},
        {"IN_CUBIC", IN_CUBIC},   {"IN_ELASTIC", IN_ELASTIC}, {"IN_EXPO", IN_EXPO},
        {"IN_QUAD", IN_QUAD},     {"IN_QUART", IN_QUART},     {"IN_QUINT", IN_QUINT},
        {"IN_SINE", IN_SINE},
        {"IN_OUT_BACK", IN_OUT_BACK},     {"IN_OUT_BOUNCE", IN_OUT_BOUNCE},
        {"IN_OUT_CIRC", IN_OUT_CIRC},     {"IN_OUT_CUBIC", IN_OUT_CUBIC},
        {"IN_OUT_ELASTIC", IN_OUT_ELASTIC}, {"IN_OUT_EXPO", IN_OUT_EXPO},
        {"IN_OUT_QUAD", IN_OUT_QUAD},     {"IN_OUT_QUART", IN_OUT_QUART},
        {"IN_OUT_QUINT", IN_OUT_QUINT},   {"IN_OUT_SINE", IN_OUT_SINE},
        {"OUT_BACK", OUT_BACK},   {"OUT_BOUNCE", OUT_BOUNCE}, {"OUT_CIRC", OUT_CIRC},
        {"OUT_CUBIC", OUT_CUBIC}, {"OUT_ELASTIC", OUT_ELASTIC}, {"OUT_EXPO", OUT_EXPO},
        {"OUT_QUAD", OUT_QUAD},   {"OUT_QUART", OUT_QUART},   {"OUT_QUINT", OUT_QUINT},
        {"OUT_SINE", OUT_SINE},
    };
    return m;
}

}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) {
        std::cerr << "usage: binary_animator_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;

    auto failF = [&](const std::string& t, const std::string& l, uint32_t got, uint32_t exp) {
        ++mism;
        if (shown++ < 40)
            std::cerr << "MISMATCH " << t << " got=" << std::hex << got << " exp=" << exp
                      << std::dec << " | " << l << "\n";
    };
    auto chkF = [&](const std::string& t, const std::string& l, float got, const std::string& exp) {
        if (fb(got) != u32(exp)) failF(t, l, fb(got), u32(exp));
    };

    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "EASE") {
            // EASE <name> <xBits> <resultBits>
            auto it = easeByName().find(p[1]);
            if (it == easeByName().end()) {
                ++mism;
                if (shown++ < 40) std::cerr << "UNKNOWN EASE " << p[1] << " | " << line << "\n";
                continue;
            }
            chkF(t, line, it->second(bf(p[2])), p[3]);
        } else if (t == "ETYPE") {
            // ETYPE <name> <xBits> <resultBits>
            auto it = etypeByName().find(p[1]);
            if (it == etypeByName().end()) {
                ++mism;
                if (shown++ < 40) std::cerr << "UNKNOWN ETYPE " << p[1] << " | " << line << "\n";
                continue;
            }
            chkF(t, line, it->second(bf(p[2])), p[3]);
        } else if (t == "BINANIM") {
            // BINANIM <len> <easeName> <script> <pBits> <resultBits>
            int len = std::stoi(p[1]);
            auto it = etypeByName().find(p[2]);
            if (it == etypeByName().end()) {
                ++mism;
                if (shown++ < 40) std::cerr << "UNKNOWN BINANIM ease " << p[2] << " | " << line << "\n";
                continue;
            }
            const std::string& script = p[3];
            bau::BinaryAnimator anim(len, it->second);
            if (script != "-") {
                for (char c : script) anim.tick(c == 'a');
            }
            chkF(t, line, anim.getFactor(bf(p[4])), p[5]);
        } else {
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << t << " | " << line << "\n";
        }
    }

    std::cout << "BinaryAnimator cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
