// Parity test for net.minecraft.util.Ease (the easing primitives). Ground truth
// generated by tools/EasingParity.java against the REAL 26.1.2 class. Each row
// carries the float input x + the expected float output, both as raw IEEE-754
// bit patterns, so the gate is BIT-EXACT.
//
//   easing_parity --cases mcpp/build/easing.tsv

#include "util/Ease.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace ease = mc::util::ease;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }

using Fn = float (*)(float);

Fn dispatch(const std::string& tag) {
    if (tag == "IN_BACK")        return ease::inBack;
    if (tag == "IN_BOUNCE")      return ease::inBounce;
    if (tag == "IN_CUBIC")       return ease::inCubic;
    if (tag == "IN_ELASTIC")     return ease::inElastic;
    if (tag == "IN_EXPO")        return ease::inExpo;
    if (tag == "IN_QUART")       return ease::inQuart;
    if (tag == "IN_QUINT")       return ease::inQuint;
    if (tag == "IN_SINE")        return ease::inSine;
    if (tag == "IN_OUT_BOUNCE")  return ease::inOutBounce;
    if (tag == "IN_OUT_CIRC")    return ease::inOutCirc;
    if (tag == "IN_OUT_CUBIC")   return ease::inOutCubic;
    if (tag == "IN_OUT_QUAD")    return ease::inOutQuad;
    if (tag == "IN_OUT_QUART")   return ease::inOutQuart;
    if (tag == "IN_OUT_QUINT")   return ease::inOutQuint;
    if (tag == "OUT_BOUNCE")     return ease::outBounce;
    if (tag == "OUT_ELASTIC")    return ease::outElastic;
    if (tag == "OUT_EXPO")       return ease::outExpo;
    if (tag == "OUT_QUAD")       return ease::outQuad;
    if (tag == "OUT_QUINT")      return ease::outQuint;
    if (tag == "OUT_SINE")       return ease::outSine;
    if (tag == "IN_OUT_SINE")    return ease::inOutSine;
    if (tag == "OUT_BACK")       return ease::outBack;
    if (tag == "OUT_QUART")      return ease::outQuart;
    if (tag == "OUT_CUBIC")      return ease::outCubic;
    if (tag == "IN_OUT_EXPO")    return ease::inOutExpo;
    if (tag == "IN_QUAD")        return ease::inQuad;
    if (tag == "OUT_CIRC")       return ease::outCirc;
    if (tag == "IN_OUT_ELASTIC") return ease::inOutElastic;
    if (tag == "IN_CIRC")        return ease::inCirc;
    if (tag == "IN_OUT_BACK")    return ease::inOutBack;
    return nullptr;
}
} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: easing_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto p = split(line);
        if (p.size() < 3) continue;
        const std::string& tag = p[0];
        Fn fn = dispatch(tag);
        if (!fn) {
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << tag << " | " << line << "\n";
            continue;
        }
        ++total;
        float x = bf(p[1]);
        float got = fn(x);
        uint32_t expBits = u32(p[2]);
        if (fb(got) != expBits) {
            ++mism;
            if (shown++ < 40)
                std::cerr << "MISMATCH " << tag << " x=" << x << " got=" << std::hex << fb(got)
                          << " exp=" << expBits << std::dec << " | " << line << "\n";
        }
    }

    std::cout << "Easing cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
