// Parity test for the C++ port of net.minecraft.util.CrudeIncrementalIntIdentityHashBiMap
// (mc::util::CrudeIncrementalIntIdentityHashBiMap in util/IdBiMap.h). Ground truth
// generated by tools/IdBiMapParity.java driving the REAL class.
//
//   id_bimap_parity --cases mcpp/build/id_bimap.tsv
//
// The TSV is a flat, in-emission-order stream of tagged rows. Emission order ==
// execution order, so we replay it row-by-row against a fresh C++ map per scenario
// and compare every observable result BIT-FOR-BIT (these are all small ints, so a
// plain equality on int is already bit-exact; we still treat them as integers and
// compare exactly, never by float value).
//
// Row TAGs (see IdBiMapParity.java):
//   KEY   <scen> <opaqueId> <identityHash>   register a distinct key (input)
//   ADD   <scen> <opaqueId> <assignedId>     map.add(key); expected assigned id
//   MAP   <scen> <opaqueId> <explicitId>     map.addMapping(key, explicitId) (input)
//   GETID <scen> <opaqueId> <getId>          expected map.getId(key)
//   BYID  <scen> <queryId> <opaqueOrMinus1>  expected opaque of map.byId(queryId)
//   SIZE  <scen> <size> <nextId>             expected size() and nextId field
//   CAP   <scen> <capacity>                  expected keys.length

#include "util/IdBiMap.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <unordered_map>
#include <vector>

using mc::util::CrudeIncrementalIntIdentityHashBiMap;
using mc::util::IdKey;
using mc::util::NULL_KEY;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
int toi(const std::string& s) { return std::stoi(s); }

// All scenario rows in file order. We process them grouped by scenario; a new
// scenario name resets the C++ map. Within a scenario, rows execute in order.
struct Row {
    std::string tag;
    std::string scen;
    int a = 0;  // opaqueId / queryId / size / capacity
    int b = 0;  // identityHash / assignedId / explicitId / getId / opaqueOrMinus1 / nextId
    bool hasB = false;
};
}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: id_bimap_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    std::vector<Row> rows;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        if (p.size() < 3) continue;
        Row r;
        r.tag = p[0];
        r.scen = p[1];
        r.a = toi(p[2]);
        if (p.size() >= 4) {
            r.b = toi(p[3]);
            r.hasB = true;
        }
        rows.push_back(std::move(r));
    }

    long long total = 0, mism = 0;
    int shown = 0;
    auto fail = [&](const std::string& what, const Row& r, long long got, long long exp) {
        ++mism;
        if (shown++ < 40)
            std::cerr << "MISMATCH " << what << " scen=" << r.scen << " a=" << r.a
                      << " got=" << got << " exp=" << exp << "\n";
    };

    // Replay state, reset per scenario.
    std::string curScen;
    // Owns the live map. unique_ptr-like via optional construction: we just rebuild
    // a fresh one when the scenario changes. The map has no default ctor for an
    // empty state, so we hold a pointer.
    CrudeIncrementalIntIdentityHashBiMap* map = nullptr;
    // opaqueId -> the IdKey we constructed for it (so ADD/MAP/GETID can re-find it).
    std::unordered_map<int, IdKey> keyByOpaque;

    // The GT create(initialCapacity) per scenario, matching IdBiMapParity.java:
    auto initialCapFor = [](const std::string& scen) -> int {
        if (scen == "basic") return 16;
        if (scen == "grow") return 4;
        if (scen == "mapseq") return 8;
        if (scen == "sparse") return 8;
        if (scen == "miss") return 16;
        if (scen == "mixed") return 6;
        return 16;  // default
    };

    auto ensureScenario = [&](const std::string& scen) {
        if (scen != curScen) {
            delete map;
            map = new CrudeIncrementalIntIdentityHashBiMap(
                CrudeIncrementalIntIdentityHashBiMap::create(initialCapFor(scen)));
            keyByOpaque.clear();
            curScen = scen;
        }
    };

    for (const auto& r : rows) {
        ensureScenario(r.scen);

        if (r.tag == "KEY") {
            // input: register distinct key opaque=r.a, identityHash=r.b
            IdKey k;
            k.id = r.a;
            k.identityHash = r.b;
            keyByOpaque[r.a] = k;
            // no comparison — pure input
        } else if (r.tag == "ADD") {
            // input: key opaque=r.a ; expected assigned id = r.b
            ++total;
            const IdKey& k = keyByOpaque.at(r.a);
            int got = map->add(k);
            if (got != r.b) fail("ADD", r, got, r.b);
        } else if (r.tag == "MAP") {
            // input: addMapping(key opaque=r.a, explicitId=r.b). No comparison —
            // the effect is observed via later GETID/BYID/SIZE/CAP rows.
            const IdKey& k = keyByOpaque.at(r.a);
            map->addMapping(k, r.b);
        } else if (r.tag == "GETID") {
            ++total;
            const IdKey& k = keyByOpaque.at(r.a);
            int got = map->getId(k);
            if (got != r.b) fail("GETID", r, got, r.b);
        } else if (r.tag == "BYID") {
            ++total;
            const IdKey& res = map->byId(r.a);
            int gotOpaque = res.isNull() ? -1 : res.id;
            if (gotOpaque != r.b) fail("BYID", r, gotOpaque, r.b);
        } else if (r.tag == "SIZE") {
            // r.a = size, r.b = nextId
            ++total;
            if (map->size() != r.a) fail("SIZE.size", r, map->size(), r.a);
            ++total;
            if (map->nextIdField() != r.b) fail("SIZE.nextId", r, map->nextIdField(), r.b);
        } else if (r.tag == "CAP") {
            // r.a = capacity (keys.length)
            ++total;
            if (map->capacity() != r.a) fail("CAP", r, map->capacity(), r.a);
        } else {
            // unknown tag — ignore
        }
    }

    delete map;

    std::cout << "IdBiMap cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
