// Parity test for the PURE interpolation math behind net.minecraft.util.Keyframe
// / KeyframeTrack / KeyframeTrackSampler (26.1.2). Ground truth generated by
// tools/KeyframeParity.java against the REAL decompiled classes. Every numeric
// output is exchanged as a raw IEEE-754 bit pattern (floats) or decimal (ints),
// so the gate is BIT-EXACT.
//
//   keyframe_parity --cases mcpp/build/keyframe.tsv
//
// Row tags:
//   EASE_<NAME>  <x:fbits>  <result:fbits>
//   BEZIER       <x1> <y1> <x2> <y2> <x>  <result>            (all float bits)
//   LERP_FLOAT   <alpha> <from> <to>  <result>                (float bits)
//   LERP_INT     <alpha:fbits> <from:dec> <to:dec>  <result:dec>
//   LERP_DEG     <maxDelta> <alpha> <from> <to>  <result>     (float bits)
//   LERP_STEP    <threshold> <alpha> <from> <to>  <result>    (float bits)
//   SAMPLE_F     <easeName> <hasPeriod> <period> <n> [<tick> <vbits>]*n  <ticks:dec> <result:fbits>

#include "util/KeyframeInterpolation.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <vector>

namespace kf = mc::util::keyframe;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }
int      i32(const std::string& s) { return static_cast<int>(std::stoll(s)); }
int64_t  i64(const std::string& s) { return static_cast<int64_t>(std::stoll(s)); }
}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: keyframe_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        if (p.empty()) continue;
        const std::string& tag = p[0];

        // Helper to record a float-bit comparison.
        auto checkF = [&](uint32_t expBits, float got) {
            ++total;
            if (fb(got) != expBits) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH " << tag << " got=" << std::hex << fb(got)
                              << " exp=" << expBits << std::dec << " | " << line << "\n";
            }
        };
        auto checkI = [&](int exp, int got) {
            ++total;
            if (got != exp) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH " << tag << " got=" << got << " exp=" << exp
                              << " | " << line << "\n";
            }
        };

        if (tag.rfind("EASE_", 0) == 0) {
            // EASE_<NAME>  <x>  <result>
            if (p.size() < 3) continue;
            const char* name = tag.c_str() + 5;  // skip "EASE_"
            auto fn = kf::easingByName(name);
            if (!fn) {
                ++total; ++mism;
                if (shown++ < 40) std::cerr << "UNKNOWN EASE " << tag << "\n";
                continue;
            }
            float x = bf(p[1]);
            checkF(u32(p[2]), fn(x));
        } else if (tag == "BEZIER") {
            // BEZIER  x1 y1 x2 y2 x  result
            if (p.size() < 7) continue;
            kf::CubicBezier bez(bf(p[1]), bf(p[2]), bf(p[3]), bf(p[4]));
            float x = bf(p[5]);
            checkF(u32(p[6]), bez.apply(x));
        } else if (tag == "LERP_FLOAT") {
            // LERP_FLOAT  alpha from to  result
            if (p.size() < 5) continue;
            float r = kf::lerpFloat(bf(p[1]), bf(p[2]), bf(p[3]));
            checkF(u32(p[4]), r);
        } else if (tag == "LERP_INT") {
            // LERP_INT  alpha(fbits) from(dec) to(dec)  result(dec)
            if (p.size() < 5) continue;
            int r = kf::lerpInt(bf(p[1]), i32(p[2]), i32(p[3]));
            checkI(i32(p[4]), r);
        } else if (tag == "LERP_DEG") {
            // LERP_DEG  maxDelta alpha from to  result
            if (p.size() < 6) continue;
            float r = kf::lerpDegrees(bf(p[1]), bf(p[2]), bf(p[3]), bf(p[4]));
            checkF(u32(p[5]), r);
        } else if (tag == "LERP_STEP") {
            // LERP_STEP  threshold alpha from to  result
            if (p.size() < 6) continue;
            float r = kf::lerpStep<float>(bf(p[1]), bf(p[2]), bf(p[3]), bf(p[4]));
            checkF(u32(p[5]), r);
        } else if (tag == "SAMPLE_F") {
            // SAMPLE_F  easeName hasPeriod period n  [tick vbits]*n  ticks result
            if (p.size() < 5) continue;
            const std::string& easeName = p[1];
            bool hasPeriod = (i32(p[2]) != 0);
            int period = i32(p[3]);
            int n = i32(p[4]);
            std::size_t idx = 5;
            if (p.size() < idx + static_cast<std::size_t>(n) * 2 + 2) continue;
            std::vector<kf::KeyframeF> keyframes;
            keyframes.reserve(static_cast<std::size_t>(n));
            for (int i = 0; i < n; ++i) {
                int tick = i32(p[idx++]);
                float val = bf(p[idx++]);
                keyframes.push_back(kf::KeyframeF{tick, val});
            }
            int64_t ticks = i64(p[idx++]);
            uint32_t expBits = u32(p[idx]);

            auto easing = kf::easingByName(easeName.c_str());
            if (!easing) {
                ++total; ++mism;
                if (shown++ < 40) std::cerr << "UNKNOWN SAMPLE EASE " << easeName << "\n";
                continue;
            }
            auto sampler = kf::KeyframeTrackSamplerF::bake(
                keyframes, easing, hasPeriod ? std::optional<int>(period) : std::nullopt);
            checkF(expBits, sampler.sample(ticks));
        } else {
            ++total; ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << tag << " | " << line << "\n";
        }
    }

    std::cout << "Keyframe cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
