// Parity test for net.minecraft.util.CubicSpline.apply(float) — the worldgen
// spline evaluation (Constant + Multipoint Hermite/linear interpolation). Ground
// truth generated by tools/CubicSplineParity.java against the real 26.1.2 class.
// Each row: <TAG>\t<coordHexBits>\t<resultHexBits>; the coordinate is the raw
// float fed straight to apply(), and floats are exchanged as raw IEEE-754 bits so
// the gate is bit-exact. We rebuild the SAME five fixed splines as the GT tool and
// recompute each row via CubicSplineFloat.h.
//
//   cubic_spline_parity --cases mcpp/build/cubic_spline.tsv

#include "CubicSplineFloat.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace cs = mc::levelgen::cubicspline;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }

// Mirror of CubicSplineParity.java's fixed splines (all coordinate = IDENTITY).

// K: a single Constant.
cs::SplinePtr splineConst() { return cs::makeConstant(7.5f); }

// M1 / FLAT: all-zero-derivative multipoint of constants.
cs::SplinePtr splineFlat() {
    std::vector<float> loc = {-1.0f, 0.0f, 0.5f, 2.0f};
    std::vector<cs::SplinePtr> val = {cs::makeConstant(-2.0f), cs::makeConstant(0.0f),
                                      cs::makeConstant(4.0f), cs::makeConstant(1.0f)};
    std::vector<float> der = {0.0f, 0.0f, 0.0f, 0.0f};
    return cs::makeMultipoint(loc, val, der);
}

// M2 / DERIV: non-zero derivatives.
cs::SplinePtr splineDeriv() {
    std::vector<float> loc = {-3.0f, -0.25f, 1.0f, 4.0f};
    std::vector<cs::SplinePtr> val = {cs::makeConstant(5.0f), cs::makeConstant(-1.0f),
                                      cs::makeConstant(2.5f), cs::makeConstant(-6.0f)};
    std::vector<float> der = {-1.5f, 0.0f, 3.0f, -0.75f};
    return cs::makeMultipoint(loc, val, der);
}

// M3 / SINGLE: one point with non-zero derivative.
cs::SplinePtr splineSingle() {
    std::vector<float> loc = {0.0f};
    std::vector<cs::SplinePtr> val = {cs::makeConstant(1.0f)};
    std::vector<float> der = {2.0f};
    return cs::makeMultipoint(loc, val, der);
}

// M4 / NESTED: one value point is itself a Multipoint.
cs::SplinePtr splineNested() {
    std::vector<float> innerLoc = {-2.0f, 3.0f};
    std::vector<cs::SplinePtr> innerVal = {cs::makeConstant(10.0f), cs::makeConstant(-4.0f)};
    std::vector<float> innerDer = {1.0f, -2.0f};
    cs::SplinePtr inner = cs::makeMultipoint(innerLoc, innerVal, innerDer);

    // The nested point's derivative is 0.0f: the public addPoint(location, sampler)
    // overload used by the GT tool fixes a child-spline point's derivative to zero.
    std::vector<float> loc = {-5.0f, 0.0f, 6.0f};
    std::vector<cs::SplinePtr> val = {cs::makeConstant(0.5f), inner, cs::makeConstant(-3.0f)};
    std::vector<float> der = {0.5f, 0.0f, 0.0f};
    return cs::makeMultipoint(loc, val, der);
}
}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) {
        std::cerr << "usage: cubic_spline_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    const cs::SplinePtr k = splineConst();
    const cs::SplinePtr flat = splineFlat();
    const cs::SplinePtr deriv = splineDeriv();
    const cs::SplinePtr single = splineSingle();
    const cs::SplinePtr nested = splineNested();

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto p = split(line);
        if (p.size() < 3) continue;
        const std::string& tag = p[0];
        const float coord = bf(p[1]);
        const uint32_t exp = u32(p[2]);

        const cs::Spline* s = nullptr;
        if (tag == "K") s = k.get();
        else if (tag == "FLAT") s = flat.get();
        else if (tag == "DERIV") s = deriv.get();
        else if (tag == "SINGLE") s = single.get();
        else if (tag == "NESTED") s = nested.get();
        else continue;

        ++total;
        const uint32_t got = fb(s->apply(coord));
        if (got != exp) {
            ++mism;
            if (shown++ < 40)
                std::cerr << "MISMATCH " << tag << " got=" << std::hex << got << " exp=" << exp
                          << std::dec << " | " << line << "\n";
        }
    }

    std::cout << "CubicSpline cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
