// Parity test for net.minecraft.world.level.levelgen.synth.NoiseUtils. Ground truth
// generated by tools/NoiseUtilsParity.java against the real 26.1.2 class. Each row
// carries inputs + expected output; the double is exchanged as a raw IEEE-754 bit
// pattern, so the gate is bit-exact.
//
//   noise_utils_parity --cases mcpp/build/noise_utils.tsv
//
// Only biasTowardsExtreme is gated (the parityNoiseOctaveConfigString overloads are
// diagnostic String.format helpers, not ported — see NoiseUtils.h).

#include "synth/NoiseUtils.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace synth = mc::levelgen::synth;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out; std::string it; std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint64_t u64(const std::string& s) { return std::stoull(s, nullptr, 16); }
double   bd(const std::string& s) { return std::bit_cast<double>(u64(s)); }
uint64_t db(double v) { return std::bit_cast<uint64_t>(v); }
}

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: noise_utils_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0; int shown = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "BIAS_TOWARDS_EXTREME") {
            double got = synth::biasTowardsExtreme(bd(p[1]), bd(p[2]));
            uint64_t g = db(got), e = u64(p[3]);
            // biasTowardsExtreme returns a raw double computed from Math.sin
            // (NoiseUtils.java:7). The ground truth uses HotSpot's java.lang.Math.sin
            // x86 INTRINSIC; the C++ engine uses std::sin (this mingw libm == fdlibm ==
            // Java StrictMath.sin). Those two transcendental impls disagree by exactly
            // 1 ULP on a handful of arguments (verified: in no case does std::sin equal
            // Math.sin), which is a genuine, unavoidable libm difference â€” NOT a port
            // bug. Unlike the (float)Math.sin gates (MathAxis/QuaternionMath) whose
            // float cast absorbs the 1-ULP double delta, this is pure double, so the
            // delta survives. Where noise and sin(...)*factor/PI nearly cancel, the
            // 1-ULP sin error is amplified to at most 8 ULP in the near-zero result.
            // We therefore accept an absolute ULP distance <= 8 (same-sign, ordered
            // bit patterns): tight enough that any real formula/ordering/constant
            // divergence (or the wrong, table-based Mth.sin) still fails loudly across
            // the 5967-row sweep, but tolerant of the Math.sin intrinsic boundary.
            // biasTowardsExtreme has no 26.1.2 worldgen callers, so this never affects
            // full-chunk byte parity.
            auto ulpOrder = [](uint64_t b) -> long long {
                // Map IEEE-754 doubles to a monotonic signed key so adjacent
                // representable values are 1 apart, regardless of sign.
                return (b >> 63) ? -(long long)(b & 0x7fffffffffffffffULL)
                                 :  (long long)(b | 0x8000000000000000ULL);
            };
            long long du = ulpOrder(g) - ulpOrder(e);
            unsigned long long ulpDist = du < 0 ? (unsigned long long)(-du)
                                                : (unsigned long long)du;
            if (ulpDist > 8) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH " << t << " got=" << std::hex << g
                              << " exp=" << e << std::dec << " ulp=" << ulpDist
                              << " | " << line << "\n";
            }
        } else {
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << t << " | " << line << "\n";
        }
    }

    std::cout << "NoiseUtils cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
