// Parity test for the C++ port of net.minecraft.util.datafix.PackedBitStorage
// (mc::util::datafix::PackedBitStorage in util/datafix/PackedBitStorage.h). Ground
// truth generated by tools/PackedBitStorageParity.java driving the REAL class.
//
//   packed_bit_storage_parity --cases mcpp/build/packed_bit_storage.tsv
//
// The TSV is a flat, in-emission-order stream of tagged rows grouped by scenario:
//   CFG   <scen> <bits> <size> <rawLen>            scenario config + long[] length
//   WSET  <scen> <index> <value>                   a set(index,value) input
//   RAW   <scen> <longIndex> <longValueDecimal>    backing data[longIndex] after writes
//   GET   <scen> <index> <value>                   expected get(index) after writes
//
// We rebuild a fresh PackedBitStorage(bits,size) per scenario, replay the WSET
// inputs IN ORDER, then compare the entire backing long[] against the RAW rows
// (the bit-packed layout — the real 1:1 trap, including straddling values and the
// negative-signed longs produced when the top data bit is set) and every GET
// readback. Longs compared bit-for-bit as int64 decimal; ints exact-equal.

#include "util/datafix/PackedBitStorage.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using mc::util::datafix::PackedBitStorage;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
int64_t tol(const std::string& s) { return std::stoll(s); }
int toi(const std::string& s) { return std::stoi(s); }

struct Scenario {
    int bits = 0;
    int size = 0;
    int rawLen = 0;
    std::vector<std::pair<int, int>> writes;   // (index, value) in order
    std::vector<std::pair<int, int64_t>> raw;  // (longIndex, expected long)
    std::vector<std::pair<int, int>> gets;     // (index, expected value)
};
}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: packed_bit_storage_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    // Preserve first-seen scenario order for stable, readable failure reports.
    std::vector<std::string> order;
    std::map<std::string, Scenario> scen;
    auto touch = [&](const std::string& name) -> Scenario& {
        auto it = scen.find(name);
        if (it == scen.end()) {
            order.push_back(name);
            return scen[name];
        }
        return it->second;
    };

    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        if (p.size() < 3) continue;
        const std::string& tag = p[0];
        const std::string& name = p[1];
        Scenario& s = touch(name);
        if (tag == "CFG") {
            s.bits = toi(p[2]);
            s.size = toi(p[3]);
            s.rawLen = toi(p[4]);
        } else if (tag == "WSET") {
            s.writes.emplace_back(toi(p[2]), toi(p[3]));
        } else if (tag == "RAW") {
            s.raw.emplace_back(toi(p[2]), tol(p[3]));
        } else if (tag == "GET") {
            s.gets.emplace_back(toi(p[2]), toi(p[3]));
        }
    }

    long long total = 0, mism = 0;
    int shown = 0;
    auto fail = [&](const std::string& what, const std::string& s, long long idx,
                    long long got, long long exp) {
        ++mism;
        if (shown++ < 50)
            std::cerr << "MISMATCH " << what << " scen=" << s << " idx=" << idx
                      << " got=" << got << " exp=" << exp << "\n";
    };

    for (const auto& name : order) {
        const Scenario& s = scen[name];

        PackedBitStorage st(s.bits, s.size);

        // 1) The freshly-allocated long[] length must equal Java's required length.
        ++total;
        if (static_cast<int>(st.getRaw().size()) != s.rawLen)
            fail("RAWLEN", name, 0, static_cast<long long>(st.getRaw().size()), s.rawLen);

        // 2) Replay the writes in order.
        for (const auto& w : s.writes) st.set(w.first, w.second);

        // 3) The packed backing store must match bit-for-bit.
        const auto& data = st.getRaw();
        for (const auto& r : s.raw) {
            ++total;
            int64_t got = (r.first >= 0 && r.first < static_cast<int>(data.size()))
                              ? data[static_cast<size_t>(r.first)]
                              : 0x7FFFFFFFFFFFFFFFLL;  // sentinel: out of range
            if (got != r.second) fail("RAW", name, r.first, got, r.second);
        }

        // 4) Every readback must match.
        for (const auto& g : s.gets) {
            ++total;
            int got = st.get(g.first);
            if (got != g.second) fail("GET", name, g.first, got, g.second);
        }
    }

    std::cout << "PackedBitStorage checks=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
