// Parity test for the C++ port of net.minecraft.world.level.material.PushReaction
// (mc::world::level::material in world/level/material/PushReaction.h). Ground
// truth generated by tools/PushReactionParity.java driving the REAL enum.
//
//   push_reaction_parity --cases mcpp/build/push_reaction.tsv
//
// Row TAGs (see PushReactionParity.java):
//   COUNT  <n>                  n = PushReaction.values().length
//   CONST  <ordinal>  <name>    one row per constant, declaration order
//
// We rebuild the enum from PushReaction.h and check, for every constant, that:
//   * our ordinal == the Java ordinal (compared BIT-FOR-BIT via std::bit_cast),
//   * our name()  == the Java Enum.name() (raw string),
//   * pushReactionByOrdinal(ordinal) round-trips to the same constant,
// and that PUSH_REACTION_COUNT matches values().length.

#include "world/level/material/PushReaction.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

using mc::world::level::material::PushReaction;
using mc::world::level::material::pushReactionByOrdinal;
using mc::world::level::material::pushReactionName;
using mc::world::level::material::pushReactionOrdinal;
using mc::world::level::material::PUSH_REACTION_COUNT;

namespace {

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
int toi(const std::string& s) { return static_cast<int>(std::stoll(s)); }

}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: push_reaction_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    long long total = 0, mism = 0;
    int shown = 0;

    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        if (p.empty()) continue;

        if (p[0] == "COUNT") {
            // COUNT <n>
            if (p.size() < 2) continue;
            int expected = toi(p[1]);
            int got = static_cast<int>(PUSH_REACTION_COUNT);
            ++total;
            if (std::bit_cast<uint32_t>(got) != std::bit_cast<uint32_t>(expected)) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH COUNT got=" << got << " exp=" << expected
                              << "\n";
            }
        } else if (p[0] == "CONST") {
            // CONST <ordinal> <name>
            if (p.size() < 3) continue;
            int ordinal = toi(p[1]);
            const std::string& name = p[2];
            ++total;

            // Reconstruct the constant from its ordinal and verify ordinal+name.
            PushReaction r = pushReactionByOrdinal(ordinal);
            int gotOrd = pushReactionOrdinal(r);
            std::string gotName(pushReactionName(r));

            bool ordOk = std::bit_cast<uint32_t>(gotOrd)
                         == std::bit_cast<uint32_t>(ordinal);
            bool nameOk = gotName == name;
            if (!ordOk || !nameOk) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH CONST ord=" << ordinal
                              << " gotName=" << gotName << " expName=" << name
                              << " gotOrd=" << gotOrd << "\n";
            }
        }
        // unknown tags ignored
    }

    std::cout << "PushReaction cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
