// Parity test for net.minecraft.world.damagesource.CombatRules (26.1.2).
// Ground truth generated by tools/CombatRulesParity.java against the real class.
// Floats are exchanged as raw IEEE-754 bit patterns and compared via std::bit_cast,
// so the gate is bit-for-bit exact.
//
//   combat_rules_parity --cases mcpp/build/combat_rules.tsv

#include "world/damagesource/CombatRules.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace cr = mc::damagesource;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out; std::string it; std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }
}

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: combat_rules_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0; int shown = 0;
    auto chkF = [&](const std::string& t, const std::string& l, float got, const std::string& exp) {
        if (fb(got) != u32(exp)) {
            ++mism;
            if (shown++ < 40)
                std::cerr << "MISMATCH " << t << " got=" << std::hex << fb(got)
                          << " exp=" << u32(exp) << std::dec << " | " << l << "\n";
        }
    };

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "ABSORB") {
            // ABSORB <damage> <totalArmor> <armorToughness> <result>
            float got = cr::getDamageAfterAbsorbNoEnchant(bf(p[1]), bf(p[2]), bf(p[3]));
            chkF(t, line, got, p[4]);
        } else if (t == "MAGIC") {
            // MAGIC <damage> <totalMagicArmor> <result>
            float got = cr::getDamageAfterMagicAbsorb(bf(p[1]), bf(p[2]));
            chkF(t, line, got, p[3]);
        } else {
            std::cerr << "unknown TAG: " << t << "\n";
            ++mism;
        }
    }

    std::cout << "CombatRules cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
