// Bit-exact parity gate for the C++ port of
// net.minecraft.util.valueproviders.TrapezoidFloat.
//
// VERIFY-EXISTING: the port already lives in
//   mcpp/src/world/level/levelgen/FloatProvider.h :: mc::valueproviders::TrapezoidFloat
// (a faithful 1:1 of the record's sample(RandomSource)). This gate re-checks it
// bit-for-bit against ground truth generated by tools/TrapezoidFloatParity.java
// (the REAL decompiled net.minecraft TrapezoidFloat).
//
//   default        -> a handful of hardcoded self-checks (no Mojang files needed)
//   --cases <tsv>  -> verify every row of the generated reference
//
// Each row from the GT tool:
//   TF  <rng>  <min_bits>  <max_bits>  <plateau_bits>  <seed>  <s0..s7 bits>
//     <rng> = "L" (LegacyRandomSource) or "X" (XoroshiroRandomSource); floats are
//     raw 32-bit hex (Float.floatToRawIntBits). 8 samples drawn in sequence from one
//     continuously-advancing RNG seeded with <seed>.

#include "../../world/level/levelgen/FloatProvider.h"
#include "../../world/level/levelgen/RandomSource.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

using mc::levelgen::LegacyRandomSource;
using mc::levelgen::RandomSource;
using mc::levelgen::XoroshiroRandomSource;
using mc::valueproviders::TrapezoidFloat;

namespace {

float bitsToFloat(const std::string& hex) {
    const uint32_t bits = static_cast<uint32_t>(std::stoul(hex, nullptr, 16));
    return std::bit_cast<float>(bits);
}

std::unique_ptr<RandomSource> makeRng(const std::string& kind, int64_t seed) {
    if (kind == "L") return std::make_unique<LegacyRandomSource>(seed);
    if (kind == "X") return std::make_unique<XoroshiroRandomSource>(seed);
    return nullptr;
}

bool verifyLine(const std::string& line, std::string& err) {
    std::istringstream in(line);
    std::string tag;
    in >> tag;
    if (tag.empty()) return true;
    if (tag != "TF") { err = "unknown tag " + tag; return false; }

    std::string rng, minHex, maxHex, plateauHex;
    long long seed = 0;
    in >> rng >> minHex >> maxHex >> plateauHex >> seed;

    const float min = bitsToFloat(minHex);
    const float max = bitsToFloat(maxHex);
    const float plateau = bitsToFloat(plateauHex);

    auto r = makeRng(rng, static_cast<int64_t>(seed));
    if (!r) { err = "unknown rng " + rng; return false; }

    const TrapezoidFloat provider(min, max, plateau);
    for (int i = 0; i < 8; ++i) {
        std::string expHex;
        if (!(in >> expHex)) { err = "TF truncated row"; return false; }
        const int32_t expected = std::bit_cast<int32_t>(bitsToFloat(expHex));
        const int32_t got = std::bit_cast<int32_t>(provider.sample(*r));
        if (got != expected) {
            err = "TF rng=" + rng + " seed=" + std::to_string(seed) + " [" +
                  std::to_string(i) + "] bits " + std::to_string(got) +
                  "!=" + std::to_string(expected);
            return false;
        }
    }
    return true;
}

// A few hardcoded rows (regenerate via tools/TrapezoidFloatParity.java if the RNG
// or formula ever changes). Format identical to the TSV.
const std::vector<std::string> kHardcoded = {
    // min=0 max=10 plateau=4 seed=0 (matches the existing height/float gate config),
    // LegacyRandomSource. Expected bits are the verified FLOAT\ttf row from the
    // certified HeightFloatProviderParityTest (same provider, same seed, 8 draws),
    // converted from its decimal int bits to %08x.
    "TF\tL\t00000000\t41200000\t40800000\t0\t40f38e1c\t40602db7\t40ac734a\t408687d0\t40d0e0a2\t4045d09b\t40912242\t411d7a43",
};

} // namespace

int main(int argc, char** argv) {
    if (argc > 2 && std::string(argv[1]) == "--cases") {
        std::ifstream f(argv[2]);
        if (!f) { std::cerr << "cannot open " << argv[2] << '\n'; return 2; }
        std::string line;
        long n = 0, bad = 0;
        while (std::getline(f, line)) {
            if (line.empty()) continue;
            std::string err;
            ++n;
            if (!verifyLine(line, err)) {
                ++bad;
                if (bad <= 20) std::cerr << "MISMATCH: " << err << '\n';
            }
        }
        std::cout << "TrapezoidFloat cases=" << n << " mismatches=" << bad << '\n';
        return bad == 0 ? 0 : 1;
    }

    long n = 0, bad = 0;
    for (const auto& line : kHardcoded) {
        std::string err;
        ++n;
        if (!verifyLine(line, err)) { ++bad; std::cerr << "FAIL: " << err << '\n'; }
    }
    std::cout << "TrapezoidFloat cases=" << n << " mismatches=" << bad << '\n';
    return bad == 0 ? 0 : 1;
}
