set(VERSION_ID "26.1.2")
set(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ASSETS_ROOT "${REPO_ROOT}/assets")
set(SRC_ASSETS_DIR "${REPO_ROOT}/mcpp/src/assets")
set(EXTRACT_DIR "${ASSETS_ROOT}/client-extract")
set(EXTRACT_ASSETS_DIR "${EXTRACT_DIR}/assets")
set(EXTRACT_DATA_DIR "${EXTRACT_DIR}/data")

file(MAKE_DIRECTORY "${ASSETS_ROOT}")
file(MAKE_DIRECTORY "${SRC_ASSETS_DIR}")

set(META_BASE "https://piston-meta.mojang.com")
set(MANIFEST_PATH "${ASSETS_ROOT}/version_manifest_v2.json")
file(DOWNLOAD "${META_BASE}/mc/game/version_manifest_v2.json" "${MANIFEST_PATH}" STATUS MANIFEST_STATUS)
list(GET MANIFEST_STATUS 0 MANIFEST_STATUS_CODE)
if(NOT MANIFEST_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Cannot download version manifest: ${MANIFEST_STATUS}")
endif()
file(READ "${MANIFEST_PATH}" MANIFEST_JSON)

string(JSON VERSION_COUNT LENGTH "${MANIFEST_JSON}" versions)
math(EXPR VERSION_LAST "${VERSION_COUNT} - 1")
set(VERSION_URL "")
foreach(I RANGE 0 ${VERSION_LAST})
    string(JSON CUR_ID GET "${MANIFEST_JSON}" versions ${I} id)
    if(CUR_ID STREQUAL VERSION_ID)
        string(JSON VERSION_URL GET "${MANIFEST_JSON}" versions ${I} url)
        break()
    endif()
endforeach()
if(VERSION_URL STREQUAL "")
    message(FATAL_ERROR "Version not found: ${VERSION_ID}")
endif()

set(VERSION_JSON_PATH "${ASSETS_ROOT}/${VERSION_ID}.json")
file(DOWNLOAD "${VERSION_URL}" "${VERSION_JSON_PATH}" STATUS VERSION_STATUS)
list(GET VERSION_STATUS 0 VERSION_STATUS_CODE)
if(NOT VERSION_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Cannot download version json: ${VERSION_STATUS}")
endif()
file(READ "${VERSION_JSON_PATH}" VERSION_JSON)
string(JSON CLIENT_URL GET "${VERSION_JSON}" downloads client url)

set(CLIENT_JAR "${ASSETS_ROOT}/client-${VERSION_ID}.jar")
if(NOT EXISTS "${CLIENT_JAR}")
    file(DOWNLOAD "${CLIENT_URL}" "${CLIENT_JAR}" STATUS CLIENT_STATUS)
    list(GET CLIENT_STATUS 0 CLIENT_STATUS_CODE)
    if(NOT CLIENT_STATUS_CODE EQUAL 0)
        message(FATAL_ERROR "Cannot download client jar: ${CLIENT_STATUS}")
    endif()
endif()

file(REMOVE_RECURSE "${EXTRACT_DIR}")
file(MAKE_DIRECTORY "${EXTRACT_DIR}")
file(ARCHIVE_EXTRACT INPUT "${CLIENT_JAR}" DESTINATION "${EXTRACT_DIR}")

file(REMOVE_RECURSE
    "${SRC_ASSETS_DIR}/minecraft/textures/block"
    "${SRC_ASSETS_DIR}/minecraft/textures/gui"
    "${SRC_ASSETS_DIR}/minecraft/textures/font"
    "${SRC_ASSETS_DIR}/minecraft/texts"
    "${SRC_ASSETS_DIR}/data/minecraft/worldgen"
    "${SRC_ASSETS_DIR}/data/minecraft/tags/block"
    "${SRC_ASSETS_DIR}/data/minecraft/tags/fluid"
    "${SRC_ASSETS_DIR}/data/minecraft/structure"
)

function(copy_asset_tree REL_PATH)
    set(SRC "${EXTRACT_ASSETS_DIR}/${REL_PATH}")
    set(DST "${SRC_ASSETS_DIR}/${REL_PATH}")
    if(NOT EXISTS "${SRC}")
        message(FATAL_ERROR "Required asset tree missing in client jar: ${REL_PATH}")
    endif()
    get_filename_component(DST_PARENT "${DST}" DIRECTORY)
    file(MAKE_DIRECTORY "${DST_PARENT}")
    file(COPY "${SRC}" DESTINATION "${DST_PARENT}")
endfunction()

function(copy_data_tree_as OUT_REL)
    foreach(SRC_REL IN LISTS ARGN)
        set(SRC "${EXTRACT_DATA_DIR}/${SRC_REL}")
        if(EXISTS "${SRC}")
            set(DST "${SRC_ASSETS_DIR}/data/${OUT_REL}")
            get_filename_component(DST_PARENT "${DST}" DIRECTORY)
            file(MAKE_DIRECTORY "${DST_PARENT}")
            file(COPY "${SRC}" DESTINATION "${DST_PARENT}")
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Required data tree missing in client jar: ${OUT_REL}")
endfunction()

function(copy_data_tree_as_optional OUT_REL)
    foreach(SRC_REL IN LISTS ARGN)
        set(SRC "${EXTRACT_DATA_DIR}/${SRC_REL}")
        if(EXISTS "${SRC}")
            set(DST "${SRC_ASSETS_DIR}/data/${OUT_REL}")
            get_filename_component(DST_PARENT "${DST}" DIRECTORY)
            file(MAKE_DIRECTORY "${DST_PARENT}")
            file(COPY "${SRC}" DESTINATION "${DST_PARENT}")
            return()
        endif()
    endforeach()
    message(STATUS "Optional data tree missing in client jar: ${OUT_REL}")
endfunction()

function(copy_required OUT_FILE)
    foreach(REL_PATH IN LISTS ARGN)
        set(SRC "${EXTRACT_ASSETS_DIR}/${REL_PATH}")
        if(EXISTS "${SRC}")
            file(COPY_FILE "${SRC}" "${SRC_ASSETS_DIR}/${OUT_FILE}" ONLY_IF_DIFFERENT)
            return()
        endif()
    endforeach()
    message(FATAL_ERROR "Required generated asset missing: ${OUT_FILE}")
endfunction()

function(copy_optional OUT_FILE)
    foreach(REL_PATH IN LISTS ARGN)
        set(SRC "${EXTRACT_ASSETS_DIR}/${REL_PATH}")
        if(EXISTS "${SRC}")
            file(COPY_FILE "${SRC}" "${SRC_ASSETS_DIR}/${OUT_FILE}" ONLY_IF_DIFFERENT)
            return()
        endif()
    endforeach()
    message(WARNING "Optional generated asset missing: ${OUT_FILE}")
endfunction()

copy_asset_tree("minecraft/textures/block")
copy_asset_tree("minecraft/textures/gui")
copy_asset_tree("minecraft/textures/font")
copy_data_tree_as("minecraft/worldgen" "minecraft/worldgen")
copy_data_tree_as("minecraft/tags/block" "minecraft/tags/block" "minecraft/tags/blocks")
copy_data_tree_as("minecraft/tags/fluid" "minecraft/tags/fluid" "minecraft/tags/fluids")
copy_data_tree_as_optional("minecraft/structure" "minecraft/structure" "minecraft/structures")

set(SPLASH_SRC "${EXTRACT_ASSETS_DIR}/minecraft/texts/splashes.txt")
if(EXISTS "${SPLASH_SRC}")
    file(MAKE_DIRECTORY "${SRC_ASSETS_DIR}/minecraft/texts")
    file(COPY_FILE "${SPLASH_SRC}" "${SRC_ASSETS_DIR}/minecraft/texts/splashes.txt" ONLY_IF_DIFFERENT)
endif()

copy_required("ascii.png" "minecraft/textures/font/ascii.png")
copy_required("gui_logo.png" "minecraft/textures/gui/title/minecraft.png")
copy_required("gui_edition.png" "minecraft/textures/gui/title/edition.png")
copy_required("gui_dirt.png" "minecraft/textures/block/dirt.png")
copy_required("gui_button.png" "minecraft/textures/gui/sprites/widget/button.png")
copy_required("gui_button_hl.png" "minecraft/textures/gui/sprites/widget/button_highlighted.png")
copy_required("splashes.txt" "minecraft/texts/splashes.txt")
copy_optional("gui_lang.png" "minecraft/textures/gui/sprites/icon/language.png" "minecraft/textures/gui/sprites/language.png")
copy_optional("gui_access.png" "minecraft/textures/gui/sprites/icon/accessibility.png" "minecraft/textures/gui/sprites/accessibility.png")

message(STATUS "Prepared runtime textures and worldgen data from client jar into ${SRC_ASSETS_DIR}")
