set(VERSION_ID "26.1.2")
set(REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/../..")
set(ASSETS_ROOT "${REPO_ROOT}/assets")
set(INDEXES_DIR "${ASSETS_ROOT}/indexes")
set(OBJECTS_DIR "${ASSETS_ROOT}/objects")

file(MAKE_DIRECTORY "${INDEXES_DIR}")
file(MAKE_DIRECTORY "${OBJECTS_DIR}")

set(META_BASE "https://piston-meta.mojang.com")
set(RES_BASE "https://resources.download.minecraft.net")
set(MANIFEST_PATH "${ASSETS_ROOT}/version_manifest_v2.json")
file(DOWNLOAD "${META_BASE}/mc/game/version_manifest_v2.json" "${MANIFEST_PATH}" STATUS MANIFEST_STATUS)
list(GET MANIFEST_STATUS 0 MANIFEST_STATUS_CODE)
if(NOT MANIFEST_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Cannot download version manifest: ${MANIFEST_STATUS}")
endif()
file(READ "${MANIFEST_PATH}" MANIFEST_JSON)

string(JSON VERSION_COUNT LENGTH "${MANIFEST_JSON}" versions)
math(EXPR VERSION_LAST "${VERSION_COUNT} - 1")
set(VERSION_URL "")
foreach(I RANGE 0 ${VERSION_LAST})
    string(JSON CUR_ID GET "${MANIFEST_JSON}" versions ${I} id)
    if(CUR_ID STREQUAL VERSION_ID)
        string(JSON VERSION_URL GET "${MANIFEST_JSON}" versions ${I} url)
        break()
    endif()
endforeach()
if(VERSION_URL STREQUAL "")
    message(FATAL_ERROR "Version not found: ${VERSION_ID}")
endif()

set(VERSION_JSON_PATH "${ASSETS_ROOT}/${VERSION_ID}.json")
file(DOWNLOAD "${VERSION_URL}" "${VERSION_JSON_PATH}" STATUS VERSION_STATUS)
list(GET VERSION_STATUS 0 VERSION_STATUS_CODE)
if(NOT VERSION_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Cannot download version json: ${VERSION_STATUS}")
endif()
file(READ "${VERSION_JSON_PATH}" VERSION_JSON)
string(JSON ASSET_INDEX_ID GET "${VERSION_JSON}" assetIndex id)
string(JSON ASSET_INDEX_URL GET "${VERSION_JSON}" assetIndex url)

set(ASSET_INDEX_PATH "${INDEXES_DIR}/${ASSET_INDEX_ID}.json")
file(DOWNLOAD "${ASSET_INDEX_URL}" "${ASSET_INDEX_PATH}" STATUS INDEX_STATUS)
list(GET INDEX_STATUS 0 INDEX_STATUS_CODE)
if(NOT INDEX_STATUS_CODE EQUAL 0)
    message(FATAL_ERROR "Cannot download asset index: ${INDEX_STATUS}")
endif()
file(READ "${ASSET_INDEX_PATH}" ASSET_INDEX_JSON)

string(JSON ASSET_COUNT LENGTH "${ASSET_INDEX_JSON}" objects)
math(EXPR ASSET_LAST "${ASSET_COUNT} - 1")
set(DOWNLOAD_COUNT 0)
set(KEEP_COUNT 0)

foreach(I RANGE 0 ${ASSET_LAST})
    string(JSON NAME MEMBER "${ASSET_INDEX_JSON}" objects ${I})
    set(KEEP FALSE)
    if(NAME MATCHES "^minecraft/textures/block/.*\\.png$")
        set(KEEP TRUE)
    elseif(NAME MATCHES "^minecraft/textures/gui/title/background/.*\\.png$")
        set(KEEP TRUE)
    elseif(NAME MATCHES "^minecraft/textures/gui/sprites/hud/.*\\.png$")
        set(KEEP TRUE)
    endif()

    if(KEEP)
        math(EXPR KEEP_COUNT "${KEEP_COUNT} + 1")
        string(JSON HASH GET "${ASSET_INDEX_JSON}" objects "${NAME}" hash)
        string(SUBSTRING "${HASH}" 0 2 PREFIX)
        set(DIR "${OBJECTS_DIR}/${PREFIX}")
        set(DST "${DIR}/${HASH}")
        if(NOT EXISTS "${DST}")
            file(MAKE_DIRECTORY "${DIR}")
            file(DOWNLOAD "${RES_BASE}/${PREFIX}/${HASH}" "${DST}" STATUS OBJECT_STATUS)
            list(GET OBJECT_STATUS 0 OBJECT_STATUS_CODE)
            if(NOT OBJECT_STATUS_CODE EQUAL 0)
                message(FATAL_ERROR "Cannot download asset ${NAME}: ${OBJECT_STATUS}")
            endif()
            math(EXPR DOWNLOAD_COUNT "${DOWNLOAD_COUNT} + 1")
        endif()
    endif()
endforeach()

message(STATUS "Prepared runtime assets: ${DOWNLOAD_COUNT} downloaded, ${KEEP_COUNT} selected into ${ASSETS_ROOT}")
