// Parity test for structure placement (RandomSpreadStructurePlacement +
// frequency reduction + exclusion zones).
//
// The expected TSV is generated by tools/StructurePlacementParity.java against
// the real 26.1.2 jar. It pins, per world seed and per random_spread structure
// set, the exact set of chunk coordinates that are "structure chunks" over the
// scanned grid. This is the deterministic where-can-structures-spawn answer that
// must match vanilla for a 1:1 world.

#include "StructurePlacement.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <string>
#include <vector>

namespace {

// Must match StructurePlacementParity.java MIN/MAX.
constexpr int kMin = -80;
constexpr int kMax = 80;

std::vector<std::string> splitTabs(const std::string& line) {
    std::vector<std::string> out;
    std::string item;
    std::istringstream ss(line);
    while (std::getline(ss, item, '\t')) out.push_back(item);
    return out;
}

std::filesystem::path findStructureSetDir() {
    for (const auto& candidate : {
             std::filesystem::path("26.1.2/data/minecraft/worldgen/structure_set"),
             std::filesystem::path("../26.1.2/data/minecraft/worldgen/structure_set") }) {
        if (std::filesystem::exists(candidate)) return candidate;
    }
    return "26.1.2/data/minecraft/worldgen/structure_set";
}

} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    }
    if (casesPath.empty()) {
        std::cerr << "usage: structure_placement_parity --cases <tsv>\n";
        return 2;
    }

    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    // Expected positives keyed by (seed, setId) -> set of (x,z).
    std::map<std::pair<int64_t, std::string>, std::set<std::pair<int, int>>> expectedHits;
    std::map<std::pair<int64_t, std::string>, int> expectedCount;
    std::vector<int64_t> seeds;

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        const auto parts = splitTabs(line);
        if (parts[0] == "SEED" && parts.size() == 2) {
            seeds.push_back(std::stoll(parts[1]));
        } else if (parts[0] == "COUNT" && parts.size() == 4) {
            expectedCount[{std::stoll(parts[1]), parts[2]}] = std::stoi(parts[3]);
        } else if (parts[0] == "HIT" && parts.size() == 5) {
            expectedHits[{std::stoll(parts[1]), parts[2]}].insert(
                {std::stoi(parts[3]), std::stoi(parts[4])});
        }
    }
    if (seeds.empty() || expectedCount.empty()) {
        std::cerr << "empty/incomplete structure placement parity data in " << casesPath << "\n";
        return 2;
    }

    const std::string dir = findStructureSetDir().string();

    int mismatches = 0;
    int shown = 0;
    long long totalHits = 0;
    int setsChecked = 0;

    for (int64_t seed : seeds) {
        const auto state = mc::levelgen::structure::StructureState::loadFromDirectory(dir, seed);
        for (const auto& [id, placement] : state.sets) {
            if (!mc::levelgen::structure::StructureState::isPlacementSupported(placement)) continue;
            const auto key = std::make_pair(seed, id);

            std::set<std::pair<int, int>> got;
            for (int x = kMin; x < kMax; ++x) {
                for (int z = kMin; z < kMax; ++z) {
                    if (state.isStructureChunk(placement, x, z)) got.insert({x, z});
                }
            }
            ++setsChecked;
            totalHits += static_cast<long long>(got.size());

            const auto expIt = expectedHits.find(key);
            const std::set<std::pair<int, int>> empty;
            const auto& exp = (expIt != expectedHits.end()) ? expIt->second : empty;

            int expCount = expectedCount.count(key) ? expectedCount[key] : -1;
            if (static_cast<int>(got.size()) != expCount) {
                ++mismatches;
                if (shown++ < 40)
                    std::cerr << "MISMATCH count seed=" << seed << " set=" << id
                              << " got=" << got.size() << " expected=" << expCount << "\n";
            }
            if (got != exp) {
                // Report a few differing coordinates.
                for (const auto& g : got) {
                    if (!exp.count(g) && shown++ < 40)
                        std::cerr << "MISMATCH extra seed=" << seed << " set=" << id
                                  << " chunk=" << g.first << "," << g.second << "\n";
                }
                for (const auto& e : exp) {
                    if (!got.count(e) && shown++ < 40)
                        std::cerr << "MISMATCH missing seed=" << seed << " set=" << id
                                  << " chunk=" << e.first << "," << e.second << "\n";
                }
                if (got != exp) ++mismatches;
            }
        }
    }

    std::cout << "StructurePlacement seeds=" << seeds.size()
              << " set-checks=" << setsChecked
              << " positives=" << totalHits
              << " mismatches=" << mismatches << "\n";
    return mismatches == 0 ? 0 : 1;
}
