// Parity test for net.minecraft.world.entity.AnimationState.
// Ground truth generated by tools/AnimationStateParity.java against the real 26.1.2
// class. Each SEQ row carries one mutation op; query rows carry the seqId + prefix
// length (+ optional ageInTicks) + the expected output. We replay the op stream on
// our 1:1 C++ port and compare bit-for-bit; floats are exchanged as raw IEEE-754
// bit patterns, ints/longs in decimal.
//
//   squid_swim_parity --cases mcpp/build/squid_swim.tsv

#include "AnimationState.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace we = mc::world::entity;

namespace {

std::vector<std::string> split(const std::string& line, char delim) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, delim)) out.push_back(it);
    // std::getline drops a trailing empty token; AnimationState ops never end in an
    // empty field, so this is fine.
    return out;
}

uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }

// One decoded mutation op from a SEQ row's encoded payload.
struct Op {
    char kind = 'X';      // 'A' start, 'I' startIfStopped, 'W' animateWhen, 'X' stop,
                          // 'F' fastForward, 'C' copyFrom
    int32_t tick = 0;     // start/startIfStopped/animateWhen tick, fastForward ticks, copyFrom srcTick
    bool cond = false;    // animateWhen condition
    float scale = 0.0f;   // fastForward timeScale
};

// Decode "A:<tick>" / "I:<tick>" / "W:<cond>:<tick>" / "X" / "F:<ticks>:<scaleBits>" / "C:<srcTick>".
Op decodeOp(const std::string& enc) {
    Op op{};
    if (enc.empty() || enc[0] == 'X') { op.kind = 'X'; return op; }
    auto parts = split(enc, ':');
    char k = parts[0][0];
    op.kind = k;
    switch (k) {
        case 'A': op.tick = std::stoi(parts[1]); break;
        case 'I': op.tick = std::stoi(parts[1]); break;
        case 'W': op.cond = (parts[1] == "1"); op.tick = std::stoi(parts[2]); break;
        case 'F': op.tick = std::stoi(parts[1]); op.scale = bf(parts[2]); break;
        case 'C': op.tick = std::stoi(parts[1]); break;
        default:  op.kind = 'X'; break;
    }
    return op;
}

void apply(we::AnimationState& a, const Op& op) {
    switch (op.kind) {
        case 'A': a.start(op.tick); break;
        case 'I': a.startIfStopped(op.tick); break;
        case 'W': a.animateWhen(op.cond, op.tick); break;
        case 'F': a.fastForward(op.tick, op.scale); break;
        case 'C': {
            we::AnimationState src;
            // Build a source whose startTick == op.tick, then copyFrom it. We have no
            // public start(MIN_VALUE) shortcut, but start(tick) sets startTick=tick
            // for any int (including Integer.MIN_VALUE, which start() simply stores).
            src.start(op.tick);
            a.copyFrom(src);
            break;
        }
        default:  a.stop(); break;
    }
}

// Rebuild a fresh object and apply the first `count` ops of the sequence.
we::AnimationState build(const std::vector<Op>& seq, size_t count) {
    we::AnimationState a;
    for (size_t i = 0; i < count && i < seq.size(); ++i) apply(a, seq[i]);
    return a;
}

}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: squid_swim_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    std::vector<std::string> lines;
    {
        std::string line;
        while (std::getline(in, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            if (!line.empty()) lines.push_back(line);
        }
    }

    // Collect the op stream per seqId (SEQ rows precede their queries, in order).
    std::map<int, std::vector<Op>> seqs;
    for (const auto& line : lines) {
        auto p = split(line, '\t');
        if (p[0] == "SEQ") {
            int seqId = std::stoi(p[1]);
            seqs[seqId].push_back(decodeOp(p[2]));
        }
    }

    long long total = 0, mism = 0;
    int shown = 0;

    auto chkI64 = [&](const std::string& t, const std::string& l, long long got,
                      const std::string& exp) {
        long long e = std::stoll(exp);
        if (got != e) {
            ++mism;
            if (shown++ < 40)
                std::cerr << "MISMATCH " << t << " got=" << got << " exp=" << e << " | " << l
                          << "\n";
        }
    };

    for (const auto& line : lines) {
        auto p = split(line, '\t');
        const std::string& t = p[0];

        if (t == "SEQ") continue;  // mutation stream, already collected
        ++total;

        if (t == "QSTATE") {
            // QSTATE <seqId> <afterOpIdx> <startTickInt> <isStarted0/1>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            auto a = build(seqs[seqId], idx);
            chkI64("QSTATE.startTick", line, a.startTickRaw(), p[3]);
            ++total;  // two checks in this row (startTick + isStarted)
            chkI64("QSTATE.isStarted", line, a.isStarted() ? 1 : 0, p[4]);
        } else if (t == "QMS") {
            // QMS <seqId> <afterOpIdx> <ageBits> <timeInMillisLong>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            float age = bf(p[3]);
            auto a = build(seqs[seqId], idx);
            chkI64(t, line, static_cast<long long>(a.getTimeInMillis(age)), p[4]);
        } else {
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << t << " | " << line << "\n";
        }
    }

    std::cout << "AnimationState cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
