// Parity test for net.minecraft.world.entity.WalkAnimationState.
// Ground truth generated by tools/WalkAnimParity.java against the real 26.1.2 class.
// Each query row carries the seqId + prefix length + (optional) partialTick + the
// expected output. We replay the SEQ op stream on our 1:1 C++ port and compare
// bit-for-bit; floats are exchanged as raw IEEE-754 bit patterns.
//
//   walk_anim_parity --cases mcpp/build/walk_anim.tsv

#include "WalkAnimationState.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace we = mc::world::entity;

namespace {

std::vector<std::string> split(const std::string& line, char delim) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, delim)) out.push_back(it);
    return out;
}

uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }

// One decoded mutation op from a SEQ row's encoded payload.
struct Op {
    char kind;            // 'U' update, 'S' setSpeed, 'X' stop
    float t = 0, fac = 0, ps = 0, s = 0;
};

// Decode "U:<t>:<f>:<ps>" / "S:<s>" / "X".
Op decodeOp(const std::string& enc) {
    Op op{};
    if (enc.empty()) { op.kind = 'X'; return op; }
    if (enc[0] == 'X') { op.kind = 'X'; return op; }
    auto parts = split(enc, ':');
    if (parts[0] == "U") {
        op.kind = 'U';
        op.t   = bf(parts[1]);
        op.fac = bf(parts[2]);
        op.ps  = bf(parts[3]);
    } else {  // "S"
        op.kind = 'S';
        op.s = bf(parts[1]);
    }
    return op;
}

void apply(we::WalkAnimationState& w, const Op& op) {
    switch (op.kind) {
        case 'U': w.update(op.t, op.fac, op.ps); break;
        case 'S': w.setSpeed(op.s); break;
        default:  w.stop(); break;
    }
}

// Rebuild a fresh object and apply the first `count` ops of the sequence.
we::WalkAnimationState build(const std::vector<Op>& seq, size_t count) {
    we::WalkAnimationState w;
    for (size_t i = 0; i < count && i < seq.size(); ++i) apply(w, seq[i]);
    return w;
}

}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) {
        std::cerr << "usage: walk_anim_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    // First pass: collect the op stream per seqId (SEQ rows are emitted in order).
    // We must read the whole file into memory anyway to apply two-pass logic, but
    // the SEQ rows precede their queries per sequence, so a streaming approach also
    // works; keep it simple and buffer all lines.
    std::vector<std::string> lines;
    {
        std::string line;
        while (std::getline(in, line)) {
            if (!line.empty() && line.back() == '\r') line.pop_back();
            if (!line.empty()) lines.push_back(line);
        }
    }

    std::map<int, std::vector<Op>> seqs;
    for (const auto& line : lines) {
        auto p = split(line, '\t');
        if (p[0] == "SEQ") {
            int seqId = std::stoi(p[1]);
            seqs[seqId].push_back(decodeOp(p[2]));
        }
    }

    long long total = 0, mism = 0;
    int shown = 0;

    auto failF = [&](const std::string& t, const std::string& l, uint32_t got, uint32_t exp) {
        ++mism;
        if (shown++ < 40)
            std::cerr << "MISMATCH " << t << " got=" << std::hex << got << " exp=" << exp
                      << std::dec << " | " << l << "\n";
    };
    auto chkF = [&](const std::string& t, const std::string& l, float got, const std::string& exp) {
        if (fb(got) != u32(exp)) failF(t, l, fb(got), u32(exp));
    };
    auto chkI = [&](const std::string& t, const std::string& l, long got, const std::string& exp) {
        long e = std::stol(exp);
        if (got != e) {
            ++mism;
            if (shown++ < 40)
                std::cerr << "MISMATCH " << t << " got=" << got << " exp=" << e << " | " << l << "\n";
        }
    };

    for (const auto& line : lines) {
        auto p = split(line, '\t');
        const std::string& t = p[0];

        if (t == "SEQ") continue;  // mutation stream, already collected
        ++total;

        if (t == "QSPEED") {
            // QSPEED <seqId> <afterOpIdx> <speedBits>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            auto w = build(seqs[seqId], idx);
            chkF(t, line, w.speed(), p[3]);
        } else if (t == "QSPEEDP") {
            // QSPEEDP <seqId> <afterOpIdx> <partialBits> <speedPartialBits>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            float partial = bf(p[3]);
            auto w = build(seqs[seqId], idx);
            chkF(t, line, w.speed(partial), p[4]);
        } else if (t == "QPOS") {
            // QPOS <seqId> <afterOpIdx> <positionBits>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            auto w = build(seqs[seqId], idx);
            chkF(t, line, w.position(), p[3]);
        } else if (t == "QPOSP") {
            // QPOSP <seqId> <afterOpIdx> <partialBits> <positionPartialBits>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            float partial = bf(p[3]);
            auto w = build(seqs[seqId], idx);
            chkF(t, line, w.position(partial), p[4]);
        } else if (t == "QMOVE") {
            // QMOVE <seqId> <afterOpIdx> <isMoving>
            int seqId = std::stoi(p[1]);
            size_t idx = static_cast<size_t>(std::stoul(p[2]));
            auto w = build(seqs[seqId], idx);
            chkI(t, line, w.isMoving() ? 1 : 0, p[3]);
        } else {
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << t << " | " << line << "\n";
        }
    }

    std::cout << "WalkAnimationState cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
