// Parity test for net.minecraft.world.level.biome.FeatureSorter.
//
// The expected TSV is generated by tools/FeatureSorterParity.java against the
// real 26.1.2 jar. It pins the global per-step PlacedFeature order whose indices
// feed WorldgenRandom.setFeatureSeed during biome decoration.

#include "BiomeFeatures.h"
#include "FeatureSorter.h"

#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {
struct ExpectedFeature {
    int step = 0;
    int index = 0;
    std::string feature;
};

std::vector<std::string> splitTabs(const std::string& line) {
    std::vector<std::string> out;
    std::string item;
    std::istringstream ss(line);
    while (std::getline(ss, item, '\t')) {
        out.push_back(item);
    }
    return out;
}

std::filesystem::path findDataRoot() {
    for (const auto& candidate : {
             std::filesystem::path("26.1.2/data/minecraft"),
             std::filesystem::path("../26.1.2/data/minecraft") }) {
        if (std::filesystem::exists(candidate / "worldgen/biome")) {
            return candidate;
        }
    }
    return "26.1.2/data/minecraft";
}
} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i) {
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) {
            casesPath = argv[++i];
        }
    }
    if (casesPath.empty()) {
        std::cerr << "usage: feature_sorter_parity --cases <tsv>\n";
        return 2;
    }

    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    std::vector<std::string> biomeSources;
    std::vector<ExpectedFeature> expected;
    int expectedStepCount = -1;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) {
            continue;
        }
        const std::vector<std::string> parts = splitTabs(line);
        if (parts.empty()) {
            continue;
        }
        if (parts[0] == "BIOME" && parts.size() == 2) {
            biomeSources.push_back(parts[1]);
        } else if (parts[0] == "STEPS" && parts.size() == 2) {
            expectedStepCount = std::stoi(parts[1]);
        } else if (parts[0] == "STEP" && parts.size() == 4) {
            expected.push_back(ExpectedFeature{
                std::stoi(parts[1]),
                std::stoi(parts[2]),
                parts[3],
            });
        }
    }

    if (biomeSources.empty() || expectedStepCount < 0) {
        std::cerr << "empty or incomplete FeatureSorter parity data in " << casesPath << "\n";
        return 2;
    }

    mc::levelgen::feature::BiomeFeatures biomeFeatures;
    try {
        const auto dataRoot = findDataRoot();
        biomeFeatures = mc::levelgen::feature::BiomeFeatures::loadFromDirectory(
            (dataRoot / "worldgen/biome").string());
    } catch (const std::exception& e) {
        std::cerr << "load error: " << e.what() << "\n";
        return 2;
    }

    const auto actualSteps = mc::levelgen::feature::FeatureSorter::buildFeaturesPerStep(
        biomeSources, biomeFeatures, true);

    int total = 0;
    int mismatches = 0;
    int shown = 0;

    if (static_cast<int>(actualSteps.size()) != expectedStepCount) {
        ++mismatches;
        std::cerr << "MISMATCH step-count got=" << actualSteps.size()
                  << " expected=" << expectedStepCount << "\n";
    }

    for (const ExpectedFeature& e : expected) {
        ++total;
        std::string got = "<missing-step>";
        if (e.step >= 0 && e.step < static_cast<int>(actualSteps.size())) {
            const auto& features = actualSteps[static_cast<std::size_t>(e.step)].features;
            if (e.index >= 0 && e.index < static_cast<int>(features.size())) {
                got = features[static_cast<std::size_t>(e.index)];
            } else {
                got = "<missing-index>";
            }
        }
        if (got != e.feature) {
            ++mismatches;
            if (shown < 80) {
                std::cerr << "MISMATCH step=" << e.step << " index=" << e.index
                          << " got=" << got << " expected=" << e.feature << "\n";
                ++shown;
            }
        }
    }

    int actualTotal = 0;
    for (const auto& step : actualSteps) {
        actualTotal += static_cast<int>(step.features.size());
    }
    if (actualTotal != total) {
        ++mismatches;
        std::cerr << "MISMATCH total feature rows got=" << actualTotal
                  << " expected=" << total << "\n";
    }

    std::cout << "FeatureSorter biomes=" << biomeSources.size()
              << " steps=" << actualSteps.size()
              << " features=" << total
              << " mismatches=" << mismatches << "\n";
    return mismatches == 0 ? 0 : 1;
}
