// Reads chunks generated by the REAL Minecraft server (server.jar) from its saved
// region (.mca) files and dumps every block as a TSV in the same format as
// FullChunkParity, so the C++ full_chunk_parity comparer can byte-match our generator
// against what the server actually wrote to disk.
//
// This is "la prueba del server": the server is run with generate-structures=false
// (see 26.1.2/server_run/server.properties), so a stored chunk == terrain + carvers +
// features/decoration, i.e. all terrain generation EXCEPT structures. Comparing our
// generator to it proves byte-match of the ported stages.
//
//   tools/run_groundtruth.ps1 -Tool ServerChunkDump -Out mcpp/build/server_chunk_cases.tsv -ToolArgs "1 0,0 1,1 -1,-1"
//      args: <seed> then any number of "cx,cz" chunk coords. Defaults if none given.
//
// Region container parsing is done by hand (version-stable); only the per-chunk NBT
// payload is parsed with the real net.minecraft.nbt.NbtIo. Block-state section layout
// is the standard 1.16+ paletted format: index = y*256 + z*16 + x (x fastest);
// bitsPerEntry = max(4, ceil(log2(paletteSize))); entries packed LSB-first and never
// spanning a long. region-file-compression=deflate => compression type 2 (zlib).
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;
import java.util.zip.InflaterInputStream;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtIo;

public class ServerChunkDump {
    static final int MIN_Y = -64;
    static final int HEIGHT = 384;
    static final String REGION_DIR = "26.1.2/server_run/world/dimensions/minecraft/overworld/region";

    static int beInt(byte[] b, int off) {
        return ((b[off] & 0xFF) << 24) | ((b[off + 1] & 0xFF) << 16)
             | ((b[off + 2] & 0xFF) << 8) | (b[off + 3] & 0xFF);
    }

    // Returns the chunk root NBT, or null if the chunk is absent in this region.
    static CompoundTag readChunkNbt(int cx, int cz) throws IOException {
        int rx = cx >> 5, rz = cz >> 5;
        Path mca = Path.of(REGION_DIR, "r." + rx + "." + rz + ".mca");
        if (!Files.exists(mca)) return null;
        byte[] file = Files.readAllBytes(mca);
        int idx = (cx & 31) + (cz & 31) * 32;
        int loc = beInt(file, idx * 4);
        if (loc == 0) return null;
        int sectorOffset = loc >>> 8;
        int start = sectorOffset * 4096;
        int length = beInt(file, start);            // includes the 1 compression byte
        int compression = file[start + 4] & 0xFF;
        byte[] payload = new byte[length - 1];
        System.arraycopy(file, start + 5, payload, 0, length - 1);
        java.io.InputStream raw = new ByteArrayInputStream(payload);
        java.io.InputStream dec;
        switch (compression) {
            case 1: dec = new GZIPInputStream(raw); break;
            case 2: dec = new InflaterInputStream(raw); break;
            case 3: dec = raw; break;
            default: throw new IOException("unsupported region compression type " + compression
                + " (external-file flag/lz4 not handled)");
        }
        try (DataInputStream dis = new DataInputStream(dec)) {
            return NbtIo.read(dis);
        }
    }

    // Decode one chunk's blocks into a [24][4096] palette-name grid (sectionIdx, yzx index).
    // Missing sections / out-of-range => "minecraft:air".
    static String[][] decodeChunk(CompoundTag root) {
        String[][] grid = new String[24][];   // grid[sectionIdx][yzxIndex] = block name
        ListTag sections = root.getListOrEmpty("sections");
        for (int i = 0; i < sections.size(); i++) {
            CompoundTag section = sections.getCompoundOrEmpty(i);
            int sectionY = section.getByteOr("Y", (byte) 0);
            int sectionIdx = sectionY - (MIN_Y >> 4);   // -4 -> 0 .. 19 -> 23
            if (sectionIdx < 0 || sectionIdx >= 24) continue;
            CompoundTag blockStates = section.getCompoundOrEmpty("block_states");
            ListTag palette = blockStates.getListOrEmpty("palette");
            int paletteSize = palette.size();
            if (paletteSize == 0) continue;
            String[] names = new String[paletteSize];
            for (int p = 0; p < paletteSize; p++) {
                names[p] = palette.getCompoundOrEmpty(p).getStringOr("Name", "minecraft:air");
            }
            String[] cells = new String[4096];
            if (paletteSize == 1) {
                java.util.Arrays.fill(cells, names[0]);
            } else {
                long[] data = blockStates.getLongArray("data").orElse(new long[0]);
                int bits = Math.max(4, 32 - Integer.numberOfLeadingZeros(paletteSize - 1));
                int valuesPerLong = 64 / bits;
                long mask = (1L << bits) - 1L;
                for (int yzx = 0; yzx < 4096; yzx++) {
                    int cell = yzx / valuesPerLong;
                    int bitIndex = (yzx % valuesPerLong) * bits;
                    int id = cell < data.length ? (int) ((data[cell] >>> bitIndex) & mask) : 0;
                    cells[yzx] = id < names.length ? names[id] : "minecraft:air";
                }
            }
            grid[sectionIdx] = cells;
        }
        return grid;
    }

    static String blockAt(String[][] grid, int lx, int y, int lz) {
        int sectionIdx = (y - MIN_Y) >> 4;
        if (sectionIdx < 0 || sectionIdx >= 24 || grid[sectionIdx] == null) return "minecraft:air";
        int localY = (y - MIN_Y) & 15;
        int yzx = localY * 256 + lz * 16 + lx;
        return grid[sectionIdx][yzx];
    }

    public static void main(String[] args) throws IOException {
        long seed = 1L;
        boolean statusScan = false;
        List<int[]> chunks = new ArrayList<>();
        for (String a : args) {
            if (a.equals("--status")) {
                statusScan = true;
            } else if (a.contains(",")) {
                String[] p = a.split(",");
                chunks.add(new int[]{ Integer.parseInt(p[0].trim()), Integer.parseInt(p[1].trim()) });
            } else {
                seed = Long.parseLong(a.trim());
            }
        }
        if (statusScan) {
            // --status: print "cx cz Status" for EVERY chunk present in every region
            // file. Used to recover the server's exact decorated set (chunks whose
            // status reached at least minecraft:features) so the GT decoration perm
            // can mirror it without guessing the forceload rect.
            Path dir = Path.of(REGION_DIR);
            try (var stream = Files.list(dir)) {
                for (Path mca : stream.filter(p -> p.getFileName().toString().endsWith(".mca")).sorted().toList()) {
                    String[] parts = mca.getFileName().toString().split("\\.");
                    int rx = Integer.parseInt(parts[1]), rz = Integer.parseInt(parts[2]);
                    byte[] file = Files.readAllBytes(mca);
                    for (int i = 0; i < 1024; i++) {
                        if (beInt(file, i * 4) == 0) continue;
                        int cx = rx * 32 + (i & 31), cz = rz * 32 + (i >> 5);
                        CompoundTag root = readChunkNbt(cx, cz);
                        System.out.println(cx + "\t" + cz + "\t" + (root == null ? "?" : root.getStringOr("Status", "?")));
                    }
                }
            }
            return;
        }
        if (chunks.isEmpty()) {
            int[][] def = { {0, 0}, {1, 1}, {-1, -1}, {2, 3}, {0, 1}, {3, -2} };
            for (int[] c : def) chunks.add(c);
        }

        java.io.PrintStream out = System.out;
        for (int[] c : chunks) {
            int cx = c[0], cz = c[1];
            CompoundTag root = readChunkNbt(cx, cz);
            if (root == null) {
                System.err.println("SKIP chunk " + cx + "," + cz + " (absent in region)");
                continue;
            }
            String status = root.getStringOr("Status", "");
            if (!status.equals("minecraft:full") && !status.equals("full")) {
                System.err.println("SKIP chunk " + cx + "," + cz + " (status=" + status + ", not full)");
                continue;
            }
            String[][] grid = decodeChunk(root);
            for (int lx = 0; lx < 16; lx++) {
                int blockX = cx * 16 + lx;
                for (int lz = 0; lz < 16; lz++) {
                    int blockZ = cz * 16 + lz;
                    for (int y = MIN_Y; y < MIN_Y + HEIGHT; y++) {
                        out.println(seed + "\t" + blockX + "\t" + blockZ + "\t" + y + "\t" + blockAt(grid, lx, y, lz));
                    }
                }
            }
            System.err.println("DUMPED chunk " + cx + "," + cz);
        }
    }
}
