// Parity test for the C++ port of net.minecraft.util.ByIdMap
// (mc::util in util/ByIdMap.h). Ground truth generated by tools/ByIdMapParity.java
// driving the REAL ByIdMap.continuous(...) / ByIdMap.sparse(...).
//
//   byidmap_parity --cases mcpp/build/byidmap.tsv
//
// Each row is a single observed lookup, recomputed here and compared BIT-FOR-BIT
// (std::bit_cast over the 32-bit result) against ground truth.
//
// Row TAGs (see ByIdMapParity.java):
//   CONT  <scen> <length> <strategyOrd> <id> <result>
//         strategyOrd: 0=ZERO 1=WRAP 2=CLAMP. result = resolved index (the int
//         payload the continuous function returned).
//   SPRS  <scen> <id> <result>
//         result = payload for id, or DEFAULT_SENTINEL when absent.
//
// We model the scenarios with Integer payloads whose id == their own int value, so
// the continuous lookup returns exactly the resolved index. The C++ side rebuilds
// the SAME std::vector<int> scenarios via mc::util::continuous / ::sparse and
// compares.

#include "util/ByIdMap.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

using mc::util::OutOfBoundsStrategy;

namespace {

constexpr int DEFAULT_SENTINEL = -999999;

std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
int toi(const std::string& s) { return static_cast<int>(std::stoll(s)); }

OutOfBoundsStrategy strategyFromOrd(int ord) {
    switch (ord) {
        case 0: return OutOfBoundsStrategy::ZERO;
        case 1: return OutOfBoundsStrategy::WRAP;
        case 2: return OutOfBoundsStrategy::CLAMP;
        default: return OutOfBoundsStrategy::ZERO;
    }
}

// The EXACT value arrays the GT tool drove (mirrored here so we build identical
// maps). idGetter is identity, so each array is a permutation of 0..length-1
// (continuous) or arbitrary distinct ids (sparse).
const std::map<std::string, std::vector<int>>& contScenarios() {
    static const std::map<std::string, std::vector<int>> m = {
        {"len1", {0}},
        {"len2", {1, 0}},
        {"len4", {2, 0, 3, 1}},
        {"len7", {6, 0, 4, 2, 5, 1, 3}},
        {"len16", {15, 1, 9, 4, 12, 0, 7, 3, 14, 6, 10, 2, 13, 5, 11, 8}},
    };
    return m;
}
const std::map<std::string, std::vector<int>>& sprsScenarios() {
    static const std::map<std::string, std::vector<int>> m = {
        {"sp_dense", {0, 1, 2, 3, 4}},
        {"sp_gaps", {0, 5, 2, 9, 3, 40, 7, 1, 12, 100, 4}},
        {"sp_neg", {-5, -1, 0, 3, 7, -100, 50}},
        {"sp_one", {42}},
    };
    return m;
}

// Build (lazily, once per scenario+strategy) the continuous lookup, and (once per
// scenario) the sparse lookup, caching the std::function so we exercise the real
// closure path rather than re-deriving the index inline.
struct ContKey {
    std::string scen;
    int ord;
    bool operator<(const ContKey& o) const {
        return scen != o.scen ? scen < o.scen : ord < o.ord;
    }
};

}  // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int i = 1; i < argc; ++i)
        if (std::string(argv[i]) == "--cases" && i + 1 < argc) casesPath = argv[++i];
    if (casesPath.empty()) {
        std::cerr << "usage: byidmap_parity --cases <tsv>\n";
        return 2;
    }
    std::ifstream in(casesPath);
    if (!in) {
        std::cerr << "cannot open " << casesPath << "\n";
        return 2;
    }

    const std::function<int(const int&)> idGetter = [](const int& v) { return v; };

    std::map<ContKey, std::function<int(int32_t)>> contFns;
    std::map<std::string, std::function<int(int32_t)>> sprsFns;

    auto contFn = [&](const std::string& scen, int ord) -> std::function<int(int32_t)>& {
        ContKey k{scen, ord};
        auto it = contFns.find(k);
        if (it == contFns.end()) {
            const auto& vals = contScenarios().at(scen);
            it = contFns
                     .emplace(k, mc::util::continuous<int>(idGetter, vals,
                                                           strategyFromOrd(ord)))
                     .first;
        }
        return it->second;
    };
    auto sprsFn = [&](const std::string& scen) -> std::function<int(int32_t)>& {
        auto it = sprsFns.find(scen);
        if (it == sprsFns.end()) {
            const auto& vals = sprsScenarios().at(scen);
            it = sprsFns
                     .emplace(scen, mc::util::sparse<int>(idGetter, vals,
                                                          DEFAULT_SENTINEL))
                     .first;
        }
        return it->second;
    };

    long long total = 0, mism = 0;
    int shown = 0;

    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        if (p.empty()) continue;

        if (p[0] == "CONT") {
            // CONT <scen> <length> <strategyOrd> <id> <result>
            if (p.size() < 6) continue;
            const std::string& scen = p[1];
            int length = toi(p[2]);
            int ord = toi(p[3]);
            int id = toi(p[4]);
            int expected = toi(p[5]);
            (void)length;  // implied by the scenario's array size
            ++total;
            int got = contFn(scen, ord)(id);
            if (std::bit_cast<uint32_t>(got) != std::bit_cast<uint32_t>(expected)) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH CONT scen=" << scen << " ord=" << ord
                              << " id=" << id << " got=" << got << " exp=" << expected
                              << "\n";
            }
        } else if (p[0] == "SPRS") {
            // SPRS <scen> <id> <result>
            if (p.size() < 4) continue;
            const std::string& scen = p[1];
            int id = toi(p[2]);
            int expected = toi(p[3]);
            ++total;
            int got = sprsFn(scen)(id);
            if (std::bit_cast<uint32_t>(got) != std::bit_cast<uint32_t>(expected)) {
                ++mism;
                if (shown++ < 40)
                    std::cerr << "MISMATCH SPRS scen=" << scen << " id=" << id
                              << " got=" << got << " exp=" << expected << "\n";
            }
        }
        // unknown tags ignored
    }

    std::cout << "ByIdMap cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
