// Parity test for net.minecraft.world.level.block.NetherVines. Ground truth
// generated by tools/NetherVinesParity.java against the REAL 26.1.2 class. Each
// row carries a seed + 16 expected growth counts drawn in sequence from ONE
// continuously-advancing LegacyRandomSource. The counts are plain ints (decimal),
// so the gate is exact.
//
//   nether_vines_parity --cases mcpp/build/nether_vines.tsv
//
// Only getBlocksToGrowWhenBonemealed is gated (the RNG-driven bone-meal growth
// loop). isValidGrowthState(BlockState) is a BlockState predicate and is out of
// scope for this pure helper — see NetherVines.h.

#include "world/level/block/NetherVines.h"
#include "world/level/levelgen/RandomSource.h"

#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out;
    std::string it;
    std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
int64_t i64(const std::string& s) { return std::stoll(s); }
int32_t i32(const std::string& s) { return static_cast<int32_t>(std::stol(s)); }
} // namespace

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: nether_vines_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0;
    int shown = 0;
    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        if (!line.empty() && line.back() == '\r') line.pop_back();
        auto p = split(line);
        if (p.empty()) continue;
        const std::string& t = p[0];

        if (t == "NV") {
            // p[1] = seed, p[2..] = 16 expected counts drawn in sequence from one
            // continuously-advancing RNG (no reseed between draws).
            int64_t seed = i64(p[1]);
            auto rng = mc::levelgen::RandomSource::create(seed);
            for (std::size_t i = 2; i < p.size(); ++i) {
                ++total;
                int32_t got = mc::world::level::block::NetherVines::getBlocksToGrowWhenBonemealed(*rng);
                int32_t exp = i32(p[i]);
                if (got != exp) {
                    ++mism;
                    if (shown++ < 40)
                        std::cerr << "MISMATCH NV seed=" << seed << " draw=" << (i - 2)
                                  << " got=" << got << " exp=" << exp << "\n";
                }
            }
        } else {
            ++total;
            ++mism;
            if (shown++ < 40) std::cerr << "UNKNOWN TAG " << t << " | " << line << "\n";
        }
    }

    std::cout << "NetherVines checks=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
