// Parity test for net.minecraft.core.Rotations (26.1.2). Ground truth generated by
// tools/RotationsParity.java against the real class. Each ROT row carries the input
// triple + the post-normalization x()/y()/z(); WRAPDEG_F rows re-verify the reused
// certified Mth.wrapDegrees(float). All floats exchanged as raw IEEE-754 bits, so the
// gate is bit-exact.
//
//   rotations_parity --cases mcpp/build/rotations.tsv

#include "core/Rotations.h"
#include "world/level/levelgen/Mth.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace mth = mc::levelgen::mth;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out; std::string it; std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
float    bf(const std::string& s) { return std::bit_cast<float>(u32(s)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }
}

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: rotations_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0; int shown = 0;
    auto failF = [&](const std::string& t, const std::string& l, uint32_t got, uint32_t exp) {
        ++mism; if (shown++ < 40)
            std::cerr << "MISMATCH " << t << " got=" << std::hex << got << " exp=" << exp
                      << std::dec << " | " << l << "\n";
    };
    auto chkF = [&](const std::string& t, const std::string& l, float got, const std::string& exp) {
        if (fb(got) != u32(exp)) failF(t, l, fb(got), u32(exp));
    };

    std::string line;
    while (std::getline(in, line)) {
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "ROT") {
            // p[1..3] = in x,y,z ; p[4..6] = expected normalized x(),y(),z()
            mc::core::Rotations r(bf(p[1]), bf(p[2]), bf(p[3]));
            chkF(t, line, r.x(), p[4]);
            chkF(t, line, r.y(), p[5]);
            chkF(t, line, r.z(), p[6]);
        } else if (t == "WRAPDEG_F") {
            chkF(t, line, mth::wrapDegrees(bf(p[1])), p[2]);
        } else {
            ++mism; if (shown++ < 40) std::cerr << "UNKNOWN_TAG " << t << "\n";
        }
    }

    std::cout << "Rotations cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
