// Reads chunks generated by the REAL Minecraft server (server.jar) from its saved
// region (.mca) files and dumps every block as a TSV in the same format as
// FullChunkParity, so the C++ full_chunk_parity comparer can byte-match our generator
// against what the server actually wrote to disk.
//
// This is "la prueba del server": the server is run with generate-structures=false
// (see 26.1.2/server_run/server.properties), so a stored chunk == terrain + carvers +
// features/decoration, i.e. all terrain generation EXCEPT structures. Comparing our
// generator to it proves byte-match of the ported stages.
//
//   tools/run_groundtruth.ps1 -Tool ServerChunkDump -Out mcpp/build/server_chunk_cases.tsv -ToolArgs "1 0,0 1,1 -1,-1"
//      args: <seed> then any number of "cx,cz" chunk coords. Defaults if none given.
//
// Region container parsing is done by hand (version-stable); the per-chunk NBT payload
// and block-state sections are decoded with Minecraft's own NbtIo and PalettedContainer
// codec, so the saved-world oracle follows the server registry and palette rules.
// region-file-compression=deflate => compression type 2 (zlib).
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.zip.GZIPInputStream;
import java.util.zip.InflaterInputStream;
import com.mojang.serialization.Codec;
import net.minecraft.SharedConstants;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.ListTag;
import net.minecraft.nbt.NbtIo;
import net.minecraft.nbt.NbtOps;
import net.minecraft.server.Bootstrap;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.level.chunk.PalettedContainer;
import net.minecraft.world.level.chunk.Strategy;

public class ServerChunkDump {
    static final int MIN_Y = -64;
    static final int HEIGHT = 384;
    static String regionDir = "26.1.2/server_run/world/dimensions/minecraft/overworld/region";

    static int beInt(byte[] b, int off) {
        return ((b[off] & 0xFF) << 24) | ((b[off + 1] & 0xFF) << 16)
             | ((b[off + 2] & 0xFF) << 8) | (b[off + 3] & 0xFF);
    }

    // Returns the chunk root NBT, or null if the chunk is absent in this region.
    static CompoundTag readChunkNbt(int cx, int cz) throws IOException {
        int rx = cx >> 5, rz = cz >> 5;
        Path mca = Path.of(regionDir, "r." + rx + "." + rz + ".mca");
        if (!Files.exists(mca)) return null;
        byte[] file = Files.readAllBytes(mca);
        int idx = (cx & 31) + (cz & 31) * 32;
        int loc = beInt(file, idx * 4);
        if (loc == 0) return null;
        int sectorOffset = loc >>> 8;
        int start = sectorOffset * 4096;
        int length = beInt(file, start);            // includes the 1 compression byte
        int compression = file[start + 4] & 0xFF;
        byte[] payload = new byte[length - 1];
        System.arraycopy(file, start + 5, payload, 0, length - 1);
        java.io.InputStream raw = new ByteArrayInputStream(payload);
        java.io.InputStream dec;
        switch (compression) {
            case 1: dec = new GZIPInputStream(raw); break;
            case 2: dec = new InflaterInputStream(raw); break;
            case 3: dec = raw; break;
            default: throw new IOException("unsupported region compression type " + compression
                + " (external-file flag/lz4 not handled)");
        }
        try (DataInputStream dis = new DataInputStream(dec)) {
            return NbtIo.read(dis);
        }
    }

    static Codec<PalettedContainer<BlockState>> blockStateCodec;

    static Codec<PalettedContainer<BlockState>> blockStateCodec() {
        if (blockStateCodec == null) {
            Strategy<BlockState> strategy = Strategy.createForBlockStates(Block.BLOCK_STATE_REGISTRY);
            blockStateCodec = PalettedContainer.codecRW(BlockState.CODEC, strategy, Blocks.AIR.defaultBlockState());
        }
        return blockStateCodec;
    }

    // Decode one chunk's blocks with Minecraft's real PalettedContainer codec.
    // Missing sections / out-of-range => "minecraft:air".
    static String[][] decodeChunk(CompoundTag root) {
        String[][] grid = new String[24][];   // grid[sectionIdx][yzxIndex] = block name
        ListTag sections = root.getListOrEmpty("sections");
        for (int i = 0; i < sections.size(); i++) {
            CompoundTag section = sections.getCompoundOrEmpty(i);
            int sectionY = section.getByteOr("Y", (byte) 0);
            int sectionIdx = sectionY - (MIN_Y >> 4);   // -4 -> 0 .. 19 -> 23
            if (sectionIdx < 0 || sectionIdx >= 24) continue;
            CompoundTag blockStates = section.getCompoundOrEmpty("block_states");
            if (blockStates.isEmpty()) continue;
            PalettedContainer<BlockState> container = blockStateCodec().parse(NbtOps.INSTANCE, blockStates)
                .getOrThrow(msg -> new IllegalStateException("block_states decode failed at section " + sectionY + ": " + msg));
            String[] cells = new String[4096];
            for (int y = 0; y < 16; y++) {
                for (int z = 0; z < 16; z++) {
                    for (int x = 0; x < 16; x++) {
                        BlockState state = container.get(x, y, z);
                        cells[y * 256 + z * 16 + x] = BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString();
                    }
                }
            }
            grid[sectionIdx] = cells;
        }
        return grid;
    }
    static String blockAt(String[][] grid, int lx, int y, int lz) {
        int sectionIdx = (y - MIN_Y) >> 4;
        if (sectionIdx < 0 || sectionIdx >= 24 || grid[sectionIdx] == null) return "minecraft:air";
        int localY = (y - MIN_Y) & 15;
        int yzx = localY * 256 + lz * 16 + lx;
        return grid[sectionIdx][yzx];
    }

    public static void main(String[] args) throws IOException {
        SharedConstants.tryDetectVersion();
        Bootstrap.bootStrap();
        java.io.PrintStream out = new java.io.PrintStream(new java.io.FileOutputStream(java.io.FileDescriptor.out), false, "US-ASCII");
        java.io.PrintStream err = new java.io.PrintStream(new java.io.FileOutputStream(java.io.FileDescriptor.err), false, "US-ASCII");
        long seed = 1L;
        boolean statusScan = false;
        List<int[]> chunks = new ArrayList<>();
        for (int ai = 0; ai < args.length; ++ai) {
            String a = args[ai];
            if (a.equals("--region") && ai + 1 < args.length) {
                regionDir = args[++ai];
            } else if (a.equals("--status")) {
                statusScan = true;
            } else if (a.contains(",")) {
                String[] p = a.split(",");
                chunks.add(new int[]{ Integer.parseInt(p[0].trim()), Integer.parseInt(p[1].trim()) });
            } else {
                seed = Long.parseLong(a.trim());
            }
        }
        if (statusScan) {
            // --status: print "cx cz Status" for EVERY chunk present in every region
            // file. Used to recover the server's exact decorated set (chunks whose
            // status reached at least minecraft:features) so the GT decoration perm
            // can mirror it without guessing the forceload rect.
            Path dir = Path.of(regionDir);
            try (var stream = Files.list(dir)) {
                for (Path mca : stream.filter(p -> p.getFileName().toString().endsWith(".mca")).sorted().toList()) {
                    String[] parts = mca.getFileName().toString().split("\\.");
                    int rx = Integer.parseInt(parts[1]), rz = Integer.parseInt(parts[2]);
                    byte[] file = Files.readAllBytes(mca);
                    for (int i = 0; i < 1024; i++) {
                        if (beInt(file, i * 4) == 0) continue;
                        int cx = rx * 32 + (i & 31), cz = rz * 32 + (i >> 5);
                        CompoundTag root = readChunkNbt(cx, cz);
                        out.println(cx + "\t" + cz + "\t" + (root == null ? "?" : root.getStringOr("Status", "?")));
                    }
                }
            }
            return;
        }
        if (chunks.isEmpty()) {
            int[][] def = { {0, 0}, {1, 1}, {-1, -1}, {2, 3}, {0, 1}, {3, -2} };
            for (int[] c : def) chunks.add(c);
        }

        for (int[] c : chunks) {
            int cx = c[0], cz = c[1];
            CompoundTag root = readChunkNbt(cx, cz);
            if (root == null) {
                err.println("SKIP chunk " + cx + "," + cz + " (absent in region)");
                continue;
            }
            String status = root.getStringOr("Status", "");
            if (!status.equals("minecraft:full") && !status.equals("full")) {
                err.println("SKIP chunk " + cx + "," + cz + " (status=" + status + ", not full)");
                continue;
            }
            String[][] grid = decodeChunk(root);
            for (int lx = 0; lx < 16; lx++) {
                int blockX = cx * 16 + lx;
                for (int lz = 0; lz < 16; lz++) {
                    int blockZ = cz * 16 + lz;
                    for (int y = MIN_Y; y < MIN_Y + HEIGHT; y++) {
                        out.println(seed + "\t" + blockX + "\t" + blockZ + "\t" + y + "\t" + blockAt(grid, lx, y, lz));
                    }
                }
            }
            err.println("DUMPED chunk " + cx + "," + cz);
        }
    }
}
