// Parity test for net.minecraft.world.item.ToolMaterial (26.1.2).
// Ground truth generated by tools/ToolMaterialParity.java against the real class.
// floats are exchanged as raw IEEE-754 bit patterns and compared via std::bit_cast;
// ints are compared decimal — so the gate is bit-for-bit exact.
//
//   tool_material_parity --cases mcpp/build/tool_material.tsv

#include "world/item/ToolMaterial.h"

#include <bit>
#include <cstdint>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace mi = mc::item;

namespace {
std::vector<std::string> split(const std::string& line) {
    std::vector<std::string> out; std::string it; std::istringstream ss(line);
    while (std::getline(ss, it, '\t')) out.push_back(it);
    return out;
}
uint32_t u32(const std::string& s) { return static_cast<uint32_t>(std::stoul(s, nullptr, 16)); }
uint32_t fb(float v) { return std::bit_cast<uint32_t>(v); }

// Map a material name to the corresponding ported instance. Returns nullptr for
// an unknown name so the caller can flag it as a mismatch (never a silent pass).
const mi::ToolMaterial* lookup(const std::string& name) {
    if (name == "WOOD")      return &mi::WOOD;
    if (name == "STONE")     return &mi::STONE;
    if (name == "COPPER")    return &mi::COPPER;
    if (name == "IRON")      return &mi::IRON;
    if (name == "DIAMOND")   return &mi::DIAMOND;
    if (name == "GOLD")      return &mi::GOLD;
    if (name == "NETHERITE") return &mi::NETHERITE;
    return nullptr;
}
}

int main(int argc, char** argv) {
    std::string casesPath;
    for (int a = 1; a < argc; ++a)
        if (std::string(argv[a]) == "--cases" && a + 1 < argc) casesPath = argv[++a];
    if (casesPath.empty()) { std::cerr << "usage: tool_material_parity --cases <tsv>\n"; return 2; }
    std::ifstream in(casesPath);
    if (!in) { std::cerr << "cannot open " << casesPath << "\n"; return 2; }

    long long total = 0, mism = 0; int shown = 0;
    auto fail = [&](const std::string& msg, const std::string& l) {
        ++mism;
        if (shown++ < 40) std::cerr << "MISMATCH " << msg << " | " << l << "\n";
    };

    std::string line;
    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();
        if (line.empty()) continue;
        auto p = split(line);
        const std::string& t = p[0];
        ++total;

        if (t == "MAT") {
            // MAT <name> <durability> <speedBits> <attackDamageBonusBits> <enchantmentValue>
            const std::string& name = p[1];
            const mi::ToolMaterial* m = lookup(name);
            if (!m) { fail("unknown material " + name, line); continue; }

            int32_t  expDur   = static_cast<int32_t>(std::stol(p[2]));
            uint32_t expSpeed = u32(p[3]);
            uint32_t expAtk   = u32(p[4]);
            int32_t  expEnch  = static_cast<int32_t>(std::stol(p[5]));

            if (m->durability != expDur)
                fail("durability got=" + std::to_string(m->durability) + " exp=" + std::to_string(expDur), line);
            if (fb(m->speed) != expSpeed)
                fail("speed", line);
            if (fb(m->attackDamageBonus) != expAtk)
                fail("attackDamageBonus", line);
            if (m->enchantmentValue != expEnch)
                fail("enchantmentValue got=" + std::to_string(m->enchantmentValue) + " exp=" + std::to_string(expEnch), line);
        } else {
            fail("unknown TAG " + t, line);
        }
    }

    std::cout << "ToolMaterial cases=" << total << " mismatches=" << mism << "\n";
    return mism == 0 ? 0 : 1;
}
